// Single source for the docs' presentation layer: the startpage grid,
// the navbar and the footer are all built from this file. Every link here
// ends up in a rendered page, so `onBrokenLinks: 'throw'` turns a stale
// entry into a build failure — keep ids matching the docs/ folder names
// and sidebarIds matching sidebars.ts.
// Node-safe on purpose (imported by docusaurus.config.ts): data only.

export type DocSection = {
  /** Matches the folder name under docs/. */
  id: string;
  label: string;
  icon: string;
  description: string;
  /** The page a startpage card and the category redirect land on. */
  intro: string;
  /** Matches a key in sidebars.ts. */
  sidebarId: string;
  /** Every main section gets its own navbar entry. */
  navbar: 'direct';
  /**
   * Position among the 'direct' navbar entries, lowest first. Entries without
   * one keep their array order behind those that have one.
   *
   * Separate from the array order on purpose: this list also drives the
   * startpage grid and the footer, where the reading order is a different
   * question from what belongs leftmost in the header.
   */
  navbarOrder?: number;
  topPages: { label: string; to: string }[];
};

export const SECTIONS: DocSection[] = [
  {
    id: 'basics',
    label: 'Basics',
    icon: '🧠',
    description:
      'Was der Grünerator ist, welche Werkzeuge es gibt, worauf er aufbaut — und wie Sprachmodelle funktionieren und wo ihre Grenzen liegen.',
    intro: '/docs/basics/intro',
    sidebarId: 'basicsSidebar',
    navbar: 'direct',
    navbarOrder: 1,
    topPages: [
      { label: 'Was ist der Grünerator?', to: '/docs/basics/intro' },
      { label: 'Welche Werkzeuge gibt es im Grünerator?', to: '/docs/basics/tools' },
      {
        label: 'Wie nachhaltig ist der Grünerator?',
        to: '/docs/basics/nachhaltigkeit',
      },
      { label: 'Wie kommen eigene Daten in den Grünerator?', to: '/docs/basics/notebook' },
      { label: 'Wie barrierefrei ist der Grünerator?', to: '/docs/basics/barrierefreiheit' },
      { label: 'Wie funktionieren Sprachmodelle?', to: '/docs/basics/wie-llms-funktionieren' },
      {
        label: 'Welche Risiken und Gefahren haben Sprachmodelle?',
        to: '/docs/basics/risiken-und-gefahren-von-llms',
      },
      {
        label: 'Wie kennzeichne ich grünerierte Inhalte?',
        to: '/docs/basics/Kennzeichnungs-Guide',
      },
    ],
  },
  {
    id: 'guides',
    label: 'Guides',
    icon: '📖',
    description:
      'Kurze Schritt-für-Schritt-Anleitungen für einzelne Aufgaben — sortiert nach Erfahrungsstand und Thema.',
    // An autogenerated sidebar rooted at `guides/` creates pages for its
    // child categories, but no `/docs/category/guides` page for the root.
    intro: '/docs/category/einsteigerinnen',
    sidebarId: 'guidesSidebar',
    navbar: 'direct',
    navbarOrder: 2,
    topPages: [
      {
        label: 'Wie erstelle ich ein Reel?',
        to: '/docs/guides/einsteigerinnen/reel-erstellen',
      },
      {
        label: 'Wie erstelle ich KI-Bilder?',
        to: '/docs/guides/einsteigerinnen/ki-bilder-erstellen',
      },
      {
        label: 'Wie erstelle ich ein gemeinsames Projekt?',
        to: '/docs/guides/einsteigerinnen/gemeinsames-projekt-erstellen',
      },
      {
        label: 'Wie erstelle ich ein eigenes Notebook?',
        to: '/docs/guides/einsteigerinnen/eigenes-notebook-erstellen',
      },
      {
        label: 'Wie binde ich die Grüne Wolke ein?',
        to: '/docs/guides/fortgeschrittene/gruene-wolke-einbinden',
      },
      {
        label: 'Wie richte ich den Grünerator für meinen Landesverband ein?',
        to: '/docs/guides/landesverbaende/landesverband-einrichten',
      },
    ],
  },
  {
    id: 'features',
    label: 'Features',
    icon: '📄',
    description: 'Chat, Office, Agentura, Notebooks und Inhalte der Landesverbände im Überblick.',
    intro: '/docs/features/intro',
    sidebarId: 'featuresSidebar',
    navbar: 'direct',
    topPages: [
      { label: 'Überblick', to: '/docs/features/intro' },
      { label: 'KI-Chat', to: '/docs/features/chat/ki-chat' },
      { label: 'Was kann ich fragen?', to: '/docs/features/chat/was-kann-ich-fragen' },
      { label: 'Office', to: '/docs/features/office' },
      { label: 'Agentura', to: '/docs/features/agentura' },
      { label: 'Notebooks', to: '/docs/features/notebooks' },
      { label: 'Landesverbände', to: '/docs/features/landesverbaende' },
    ],
  },
  {
    id: 'sonstiges',
    label: 'Sonstiges',
    icon: '🗃️',
    description: 'Was in keinen der anderen Bereiche gehört.',
    intro: '/docs/sonstiges/inhaltsdatenbank',
    sidebarId: 'sonstigesSidebar',
    navbar: 'direct',
    topPages: [
      { label: 'Einstellungen', to: '/docs/sonstiges/einstellungen' },
      {
        label: 'Was kann ich den Grünerator-MCP-Server fragen?',
        to: '/docs/sonstiges/mcp-was-kann-ich-fragen',
      },
      { label: 'Inhaltsdatenbank', to: '/docs/sonstiges/inhaltsdatenbank' },
      {
        label: 'Wie diese Doku entsteht',
        to: '/docs/sonstiges/wie-diese-doku-entsteht',
      },
    ],
  },
];

export type QuickTask = { label: string; description: string; to: string };

export const QUICK_TASKS: QuickTask[] = [
  {
    label: 'Fragen stellen & Texte schreiben',
    description: 'Anträge, Reden und Pressemitteilungen direkt im Chat entwerfen.',
    to: '/docs/features/chat/was-kann-ich-fragen',
  },
  {
    label: 'Gemeinsam an einem Dokument arbeiten',
    description: 'Texte in Echtzeit zu mehreren schreiben, teilen und versionieren.',
    to: '/docs/features/dokumente',
  },
  {
    label: 'Eine Präsentation bauen',
    description: 'Folien anlegen, gestalten und als PDF oder PPTX exportieren.',
    to: '/docs/features/praesentationen',
  },
  {
    label: 'Für deinen Landesverband einrichten',
    description: 'Einmal die Rolle hinterlegen — danach kennt der Grünerator euren Stil.',
    to: '/docs/guides/landesverbaende/landesverband-einrichten',
  },
  {
    label: 'Eigenes Wissen anlegen',
    description: 'Ein Notebook mit euren Dokumenten und Webseiten füttern.',
    to: '/docs/guides/einsteigerinnen/eigenes-notebook-erstellen',
  },
  {
    label: 'Mit anderen Tools verbinden',
    description: 'Konnektoren einrichten — vom Kalender bis zur Grünen Wolke.',
    to: '/docs/guides/fortgeschrittene/konnektoren-einrichten',
  },
];

// Small utilities that don't fit the section grid.
export const EXTRA_LINKS = {
  webinare: { label: 'Webinare', to: '/docs/webinare' },
  archiv: { label: 'Archiv', to: '/docs/category/archiv' },
  bildnachweise: { label: 'Bildnachweise', to: '/docs/bildnachweise' },
} as const;
