/**
 * Auto-generated LQIP (Low Quality Image Placeholder) map.
 * Generated by scripts/optimize-images.mjs
 * Do not edit manually.
 */
export const lqipMap: Record<string, string> = {
  '/imagine/previews/dreizeilen-preview.png':
    'data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADQBACdASoUABkAPzmMulYvKSWjqA1R4CcJYgC3uAUabeI3+Rt2ZADnYJz4u8SNkAD+OnhZ8NqykzncO7J454z5oGOoLRWX1CWaFByB3DSCk/TQTd3HLLp0y1gy4BipSm18ej+ulwydDDiU19HPKa2YPAQAObg7FfNgS+VP54OFmmqLVE8ZHx65ul6FAAAA',
  '/imagine/previews/headline-preview.png':
    'data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAACwBACdASoUABkAPzmOv1evKaajqAqp4CcJQBlAMY7ODDKPbP5Moqe7JKykF84AAP7eXmkEBxpFUPwTHbSq7DJKtaT5CNUm69VuU/cnbtG66RsnMlMr5yhxCgVEfrS9NzuNhRA+fJqUjqfUjX467bmoAj0X4g9MqnjQpR3Hl2CEU1om4k9SZj6eBsyFUV5Qv0Zfi7gKZR/dZGSpveS43aG3IAWRAKAA',
  '/imagine/previews/info-preview.png':
    'data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACQBACdASoUABkAPzmSulgvKiUjqAqp4CcJQBkLgiL3hVSZShjPfdSfcMrq0OAA/rioO81MbIydoZXDJm1ISzm6x3vS1wcMnzeIsqHfN6RPtde85ceKa+sD/YaPmAzGO1MwItCGmTTp0CRfUzqgteOUxtb+AA==',
  '/imagine/previews/simple-preview.png':
    'data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAACQBQCdASoUABkAPzmAu1OvJ6YisBgMAeAnCWwAnTKEdNAVlvOPndQTvsT3BYFOwUJwrSgXcADh8OdZdeW2thdk8j8mmME4I+b4ze08ru7DN78MM91Q3sq8R/P89HHULiQMPOB92pgEcaqntb23318IH49sIL5oNDgaTKhGySnMmybaxScbO6QIPJCER4OdJZ/bc5DwoDF403jUq9d96REfOT6CrMM6geC01KPJyJuvE6n5EG0wDKckpIJJyAAA',
  '/imagine/previews/templates-preview.jpg':
    'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJQBOgAbjG2jkozUwAAP6/dricepxgQvv/5W7yW/aXdgY31kHIZdd5PO9RPUX2DXpVNV8hAf2ooe7mmmAOwltUo44Q1+xcCAA=',
  '/imagine/previews/veranstaltung-preview.png':
    'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQBACdASoUABkAPzmUwVmvKicjqAgB4CcJagCuLf/gHyEgDRFmFKdd3W3hAVTjUAD8zy8Pbua/eW/U9x/XSAI9DROs5isE6poR7mHZG7a4WiAJnT6i7HlGT0J6SGL964y/SyNr0esLQFQQW4OcBRy928cZNwJEBIAAAA==',
  '/imagine/previews/vorlagen-preview.jpg':
    'data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAABQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJbACdMoAC2Nq2YADW2ptk4Qm7TRcEKUGZ+c1Tb5PMNp0uS/HI/431gW+m1d00QfUE04AA',
  '/imagine/previews/zitat-preview.png':
    'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASoUABkAPzmUwVmvKicjqAgB4CcJQBibAZ4pBmjVWiyssIq9Tb61Hm2AAPxysjAoidNPczx4CgRlhxU94yo1BnXQ0IPkPlqI4XoVN4mCTaCoJfpG03fRfWLsxwPQJFC4FUiQT/KmnZHd3PDDMfEPHHvAHZAAAA==',
  '/imagine/previews/zitat-pure-preview.png':
    'data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQBACdASoUABkAPzmKuFOvKiUisBgMAeAnCWMAuwAPQu3rDrqJq34BGrgAAPxaSKwggYt8i04XpXGL7GOrVb/BskU184d3bV/lGvXdplwjOX4sPIdXIMvyAAA=',
  '/imagine/variants/editorial.png':
    'data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABwBQCdASoUABkAPzmSu1gvKiWjqAqp4CcJQBibAfAQ4hzvP33Z+8BFRvUbhKuQVEGSPkAAAN9JIxG77IE3N+e+udq4KSO7xq9+Lz21Vj2SwkQHUylgIrWxff+dIr4UTmgR+cJjIn0PmNdstP3MjForzgrIAmnmFi9mN6icXWO6sAR7Pmva4/9C/t1aWDErC/1Rx36P6ryFNuj3EO2pbhyaVF4AqPd+XCZYAA==',
  '/imagine/variants/pixel-art.png':
    'data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABQBQCdASoUABkAPzmSvFgvKiWjqAqp4CcJaACsMxgBf4pCoAmh0Z6gM2IYOGO3fzmv0wwA/oztEw87bWSlEqFW4oIcBQW7h+Etl55UIa74TRIdMWkMju6iCrXVkRvFgBeCL4EQv32Kx+ewKYhJ8eEJ+Iaqdb/dWRsbn8J8SBWdccMI2gT1fbGL0Ca+YmUX+IjkTJSGZ10oadm1GIQ5M+iByZlYlgAA',
  '/imagine/variants/realistic-photo.png':
    'data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAABwBQCdASoUABkAPzmOvlevKaYjqAqp4CcJQBjRv/wD5fn23nX2oy0w8S/vw/txisCEIaWAAP7TMbCykzgjE8yBcMWJZgfpRSabhvT4I72AMSi4kTLyVF13DyzGeZNBMiTCME+zeF6nVle6FjVFYQLlEi6I9bdhCrFsna4HQvgwBni1GdM+JO5N6uUXLiTbbCxzbXLQs/Gl7EOWFRyaWfnWmCAEkNQNjR1RtKhBNdy1gAAA',
  '/imagine/variants/soft-illustration.png':
    'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASoUABkAPzmIuVOvKSWisAgB4CcJYwDLLCKUcJPPF67cMo6N0uDT5BmcAP7emepV+6zXMv8OyC4OkZ9yowzJQXLQ+upoY4Q/cBCdCMwjIqdYof85/BRY+kSqChTIEAHnoloalO4xnisEq47WAO05oMM0gAAAAA==',
  '/imagine/variants-pure/editorial.png':
    'data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACQBACdASoUABkAPzmUwFmvKaajqAgB4CcJYgAAFVhfbu4OL6DsDHF6cyh6hxwA/iNkMlCi8A+REhZE3pSZjqxrGd7VBQ07xrm6nKflLtPFXbrAv/waAuLGuzV+E7VlVatfDpGgCt98HwmNGvazm8nwDWhxEdEuPSr569KiiRo9ywvF6KOcyqeTcsGUT9IfQ60yJ4cN5r3aFbxGiAA=',
  '/imagine/variants-pure/pixel-art.png':
    'data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAACQBQCdASoUABkAPzmSv1mvKaajqAgB4CcJaAC7IKnqWQfBXSyluBcMxl8UBJYXkhuQYXNDQADwMre+0NM/HJb0kOigehtT9qsdc03s5iVyDYeEuY5LHT2FDnr7mN00FYN65brsjyKaucFjD8lupwlD2tCUfFXevvol4yu345MKm5EogRxsc6pFYs2UI79tRuPk7P5EEtZtRdSV/CV7kDxBPGujav5RfxaECyT4nJ2YxgUGj+U++r4AAAA=',
  '/imagine/variants-pure/realistic-photo.png':
    'data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAACwBQCdASoUABkAPzmSv1mvKaajqAgB4CcJZAC+eyHOZY7Q4RWkw5Fc5R9IaRZc4hvPlHPbFbAA+4+Gj3w1plfUPrBjYCVRJ9Q+22NdZkKF5h4jk6MBvW4qf86RYWBmX1TaQ1CbBENJ4rdZXJV+Njrl3qEBnv9VZCHOTTJnhyyfMnWBtAXXx9rupCXXk6g1Qtx0rF3AI4F+W+pnwq8YrewA',
  '/imagine/variants-pure/soft-illustration.png':
    'data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASoUABkAPzmOwFcvKacjqAqp4CcJQBhuAXZXcjfUDtyfxuM9qMAA+bSJhZzj7Jzc+/BmrdhiwL1pXNUGUvCOS2b+0H8kj5g9ydtXX+OMNZhz1ObepHqfPCt73ViZqp22fGbvl7WcviyfgAAA',
  '/imagine/green-street-example.png':
    'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJZgAAKbmdQZxhwAD8X/qxQ1Dq00tTyeVgG8W8OZ49ptPPMflI8Otu9inq8l5WABh3gmZi2Iwa/2iMmjORswAA',
};
