/**
 * Type definitions for SimpleInteractiveGenerator
 * Defines interfaces for interactive question generation and session management
 */

import type { PromptAssemblyResult, Locale } from './promptAssembly.js';
import type { AIWorkerPool } from '../../../workers/types.js';
import type { Request } from 'express';

export type { AIWorkerPool };

/**
 * Request to AI worker pool
 */
export interface AIWorkerRequest {
  /** Type of AI request */
  type: string;
  /** System prompt for the AI */
  systemPrompt: string;
  /** Conversation messages */
  messages: Array<{ role: string; content: string }>;
  /** Additional options for the AI request */
  options?: {
    max_tokens?: number | undefined;
    temperature?: number | undefined;
    tools?: ToolSchema[] | undefined;
    [key: string]: unknown;
  };
}

/**
 * Response from AI worker pool
 */
export interface AIWorkerResponse {
  /** Whether the request was successful */
  success: boolean;
  /** Content returned from the AI */
  content?: string | undefined;
  /** Error message if failed */
  error?: string | undefined;
  /** Tool calls made by the AI */
  tool_calls?: ToolCall[] | undefined;
  /** Usage statistics */
  metadata?: {
    usage?: {
      input_tokens?: number | undefined;
      output_tokens?: number | undefined;
      total_tokens?: number | undefined;
    };
  };
}

/**
 * Tool schema for AI function calling
 */
export interface ToolSchema {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
}

/**
 * Tool call from AI response
 */
export interface ToolCall {
  id?: string | undefined;
  name: string;
  input: string | Record<string, unknown>;
}

/**
 * Question generated by AI
 */
export interface GeneratedQuestion {
  id: string;
  text: string;
  type: string;
  uncertainty?: string | undefined;
  questionFormat: 'multiple_choice' | 'text' | 'number';
  options?: string[] | undefined;
  optionEmojis?: string[] | undefined;
  allowCustom?: boolean | undefined;
  allowMultiSelect?: boolean | undefined;
  skipOption?: string | boolean | undefined;
}

/**
 * AI question generation function arguments
 */
export interface QuestionGenerationArgs {
  needsClarification: boolean;
  confidenceReason?: string | undefined;
  questions?: Array<{
    id?: string | undefined;
    text: string;
    uncertainty?: string | undefined;
    options?: string[] | undefined;
    emojis?: string[] | undefined;
  }>;
}

/**
 * Result of question generation
 */
export interface QuestionGenerationResult {
  needsClarification: boolean;
  questions: GeneratedQuestion[];
  confidenceReason: string;
}

/**
 * Question defaults from config
 */
export interface QuestionDefaults {
  questionFormat?: 'multiple_choice' | 'text' | 'number' | undefined;
  allowCustom?: boolean | undefined;
  allowMultiSelect?: boolean | undefined;
  skipOption?: string | boolean | undefined;
}

/**
 * Prompt configuration for question generation
 */
export interface QuestionPromptConfig {
  systemPrompt: string;
  generationPrompt: string;
  toolSchema: ToolSchema;
  questionDefaults?: QuestionDefaults | undefined;
  options?: {
    max_tokens?: number | undefined;
    temperature?: number | undefined;
    [key: string]: unknown;
  };
}

/**
 * State for generating clarifying questions
 */
export interface QuestionGenerationState {
  inhalt: string;
  requestType: string;
  generatorType: string;
  locale: string;
  aiWorkerPool: AIWorkerPool;
  req: Request;
}

/**
 * Answers to questions (question ID -> answer)
 */
export type QuestionAnswers = Record<string, string | string[]>;

/**
 * Structured answers extracted from Q&A
 */
export interface StructuredAnswers {
  scope: string[];
  audience: string | null;
  tone: string | null;
  facts: string[];
  structure: string | null;
  actionType: string | null;
  painPoint: string | null;
  beneficiaries: string[];
  budget: string | null;
  history: string | null;
  urgency: string | null;
}

/**
 * Web search result
 */
export interface WebSearchResult {
  results: Array<{
    title: string;
    url: string;
    content_snippets?: string | undefined;
    snippet?: string | undefined;
  }>;
  sources: Array<{
    title: string;
    url: string;
    snippet: string;
  }>;
}

/**
 * Web search service interface
 */
export interface SearxngService {
  performWebSearch(
    query: string,
    options: {
      maxResults?: number | undefined;
      language?: string | undefined;
    }
  ): Promise<{
    success: boolean;
    results?: Array<{
      title: string;
      url: string;
      content_snippets?: string | undefined;
      snippet?: string | undefined;
    }>;
  }>;
}

/**
 * Enrichment request for document processing
 */
export interface EnrichmentRequest {
  inhalt: string;
  requestType: string;
  userClarifications?: StructuredAnswers | undefined;
}

/**
 * Enriched context from request enrichment
 */
export interface EnrichedContext {
  documents?: Array<{
    title: string;
    content: string;
    source_url?: string | undefined;
    metadata?: Record<string, unknown> | undefined;
  }>;
  knowledge?: string[] | undefined;
}

/**
 * Prompt context for assembly (compatible with PromptAssemblyState)
 */
export interface PromptContext {
  systemRole: string;
  request: {
    inhalt: string;
    requestType: string;
    locale: Locale;
  };
  documents: Array<{
    title: string;
    content: string;
    source_url?: string | undefined;
    metadata?: Record<string, unknown> | undefined;
  }>;
  knowledge: string[];
  locale: Locale;
}

/**
 * Re-export PromptAssemblyResult as AssembledPromptResult for clarity
 */
export type AssembledPromptResult = PromptAssemblyResult;

/**
 * Generation result
 */
export interface GenerationResult {
  content: string;
  metadata?: {
    usage?: {
      input_tokens?: number | undefined;
      output_tokens?: number | undefined;
      total_tokens?: number | undefined;
    } | undefined;
  } | undefined;
}

/**
 * Session data stored in Redis
 */
export interface InteractiveSession {
  sessionId: string;
  conversationState: 'questions_asked' | 'generating' | 'completed';
  inhalt: string;
  requestType: string;
  generatorType: string;
  locale: Locale;
  questionRound: number;
  questions: GeneratedQuestion[];
  answers: {
    round1?: QuestionAnswers | undefined;
  };
  finalResult?: string | undefined;
  metadata: {
    startTime: number;
    completedAt?: number | undefined;
    duration?: number | undefined;
    confidenceReason?: string | undefined;
  };
  [key: string]: unknown;
}

/**
 * Parameters for initiateInteractiveGenerator
 */
export interface InitiateGeneratorParams {
  userId: string;
  inhalt: string;
  requestType: string;
  generatorType?: string | undefined;
  locale?: Locale | undefined;
  aiWorkerPool: AIWorkerPool;
  req: Request;
}

/**
 * Result from initiateInteractiveGenerator
 */
export interface InitiateGeneratorResult {
  status: 'success' | 'completed' | 'error';
  sessionId: string;
  conversationState: 'questions_asked' | 'completed';
  questions?: GeneratedQuestion[] | undefined;
  questionRound?: number | undefined;
  finalResult?: string | undefined;
  metadata?: {
    questionCount?: number | undefined;
    skippedQuestions?: boolean | undefined;
    confidenceReason?: string | undefined;
  };
  message?: string | undefined;
  error?: string | undefined;
}

/**
 * Parameters for continueInteractiveGenerator
 */
export interface ContinueGeneratorParams {
  userId: string;
  sessionId: string;
  answers: QuestionAnswers;
  aiWorkerPool: AIWorkerPool;
  req: Request;
}

/**
 * Result from continueInteractiveGenerator
 */
export interface ContinueGeneratorResult {
  status: 'completed' | 'error';
  sessionId: string;
  conversationState: 'completed';
  finalResult?: string | undefined;
  metadata?: {
    completedAt: number;
    duration: number;
  };
  message?: string | undefined;
  error?: string | undefined;
}

/**
 * Parameters for generateFinalResult
 */
export interface GenerateFinalResultParams {
  userId: string;
  sessionId: string;
  inhalt: string;
  requestType: string;
  generatorType?: string | undefined;
  locale?: Locale | undefined;
  questions?: GeneratedQuestion[] | undefined;
  answers?: QuestionAnswers | undefined;
  aiWorkerPool: AIWorkerPool;
  req: Request;
}

/**
 * Generator prompt configuration
 */
export interface GeneratorConfig {
  systemRole: string;
  systemRoleExtensions?: Record<string, string> | undefined;
  systemRoleAppendix?: string | undefined;
  options?: {
    max_tokens?: number | undefined;
    temperature?: number | undefined;
    [key: string]: unknown;
  };
}
