import {
  PiAnchor,
  PiBuildings,
  PiChatCircle,
  PiFacebookLogo,
  PiFileText,
  PiFlowerLight,
  PiInstagramLogo,
  PiLightbulb,
  PiLinkedinLogo,
  PiListChecks,
  PiMicrophoneStage,
  PiNewspaper,
  PiTiktokLogo,
  PiTranslate,
  PiTree,
  PiWaves,
  PiXLogo,
} from 'react-icons/pi';

import type { SystemAgentId } from './system.js';
import type { Skill } from './types.js';

type SystemSkill = Skill & { identifier: SystemAgentId };

export const SKILLS = [
  {
    identifier: 'gruenerator-antrag',
    title: 'Antrag',
    description: 'Anträge & Anfragen',
    icon: PiFileText,
    avatar: '📝',
    backgroundColor: '#316049',
    mention: 'antrag',
    skillCategory: 'dokumente',
    isSystemDefault: true,
    promptTemplate: 'Schreibe einen Antrag zum Thema: ',
  },
  {
    identifier: 'gruenerator-buergerservice',
    title: 'Bürger*innenanfragen',
    description: 'Bürger*innenanfragen beantworten',
    icon: PiChatCircle,
    avatar: '💬',
    backgroundColor: '#316049',
    mention: 'bürgerservice',
    skillCategory: 'presse',
    promptTemplate: 'Beantworte folgende Anfrage: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'Pressemitteilung',
    description: 'Pressemitteilungen verfassen',
    icon: PiNewspaper,
    avatar: '📰',
    backgroundColor: '#316049',
    mention: 'presse',
    contextPrefix: '[Plattform: Pressemitteilung]',
    skillCategory: 'presse',
    isSystemDefault: true,
    promptTemplate: 'Schreibe eine PM zum Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'Instagram',
    description: 'Instagram-Posts & Captions',
    icon: PiInstagramLogo,
    avatar: '📸',
    backgroundColor: '#316049',
    mention: 'instagram',
    contextPrefix: '[Plattform: Instagram]',
    skillCategory: 'social',
    isSystemDefault: true,
    promptTemplate: 'Post zu folgendem Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'Facebook',
    description: 'Facebook-Posts & Beiträge',
    icon: PiFacebookLogo,
    avatar: '👍',
    backgroundColor: '#316049',
    mention: 'facebook',
    contextPrefix: '[Plattform: Facebook]',
    skillCategory: 'social',
    promptTemplate: 'Beitrag zu folgendem Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'Twitter / X',
    description: 'Tweets & Threads',
    icon: PiXLogo,
    avatar: '🐦',
    backgroundColor: '#316049',
    mention: 'twitter',
    contextPrefix: '[Plattform: Twitter]',
    skillCategory: 'social',
    promptTemplate: 'Tweet zu folgendem Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'LinkedIn',
    description: 'LinkedIn-Posts & Artikel',
    icon: PiLinkedinLogo,
    avatar: '💼',
    backgroundColor: '#316049',
    mention: 'linkedin',
    contextPrefix: '[Plattform: LinkedIn]',
    skillCategory: 'social',
    promptTemplate: 'LinkedIn-Post zu: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'Reel / TikTok',
    description: 'Reel- & TikTok-Skripte',
    icon: PiTiktokLogo,
    avatar: '🎬',
    backgroundColor: '#316049',
    mention: 'reel',
    contextPrefix: '[Plattform: Reel/TikTok-Skript]',
    skillCategory: 'social',
    promptTemplate: 'Skript zu folgendem Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'Aktionsideen',
    description: 'Kreative Aktionsideen entwickeln',
    icon: PiLightbulb,
    avatar: '💡',
    backgroundColor: '#316049',
    mention: 'aktion',
    contextPrefix: '[Plattform: Aktionsideen]',
    skillCategory: 'sonstiges',
    promptTemplate: 'Entwickle Aktionsideen zu: ',
  },
  {
    identifier: 'gruenerator-rede-schreiber',
    title: 'Rede',
    description: 'Politische Reden',
    icon: PiMicrophoneStage,
    avatar: '🎙️',
    backgroundColor: '#316049',
    mention: 'rede',
    skillCategory: 'presse',
    promptTemplate: 'Schreibe eine Rede zum Thema: ',
  },
  {
    identifier: 'gruenerator-wahlprogramm',
    title: 'Wahlprogramm',
    description: 'Programmkapitel',
    icon: PiListChecks,
    avatar: '📋',
    backgroundColor: '#316049',
    mention: 'wahlprogramm',
    skillCategory: 'dokumente',
  },
  {
    identifier: 'gruenerator-leichte-sprache',
    title: 'Leichte Sprache',
    description: 'Texte in Leichte Sprache übersetzen',
    icon: PiTranslate,
    avatar: '🗣️',
    backgroundColor: '#316049',
    mention: 'leichte-sprache',
    skillCategory: 'sonstiges',
    promptTemplate: 'Übersetze folgenden Text in Leichte Sprache: ',
  },
  // ─── Per-Landesverband shortcuts ───
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit-berlin',
    title: 'PM Berlin',
    description: 'Pressemitteilung im Stil Grüne Berlin',
    icon: PiBuildings,
    avatar: '🐻',
    backgroundColor: '#316049',
    mention: 'presse-berlin',
    contextPrefix: '[LV: Berlin / Modus: PM]',
    skillCategory: 'presse',
    promptTemplate: 'Schreibe eine Pressemitteilung im Stil Grüne Berlin zum Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit-berlin',
    title: 'Social Berlin',
    description: 'Social-Media-Post im Stil Grüne Berlin',
    icon: PiBuildings,
    avatar: '🐻',
    backgroundColor: '#316049',
    mention: 'social-berlin',
    contextPrefix: '[LV: Berlin / Modus: Social Media]',
    skillCategory: 'social',
    promptTemplate:
      'Erstelle Social-Media-Posts im Stil Grüne Berlin (Facebook, Instagram, Twitter/X, LinkedIn) zum Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit-hamburg',
    title: 'PM Hamburg',
    description: 'Pressemitteilung im Stil Grüne Hamburg',
    icon: PiAnchor,
    avatar: '⚓',
    backgroundColor: '#316049',
    mention: 'presse-hamburg',
    contextPrefix: '[LV: Hamburg / Modus: PM]',
    skillCategory: 'presse',
    promptTemplate: 'Schreibe eine Pressemitteilung im Stil Grüne Hamburg zum Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit-hamburg',
    title: 'Social Hamburg',
    description: 'Social-Media-Post im Stil Grüne Hamburg',
    icon: PiAnchor,
    avatar: '⚓',
    backgroundColor: '#316049',
    mention: 'social-hamburg',
    contextPrefix: '[LV: Hamburg / Modus: Social Media]',
    skillCategory: 'social',
    promptTemplate: 'Erstelle Social-Media-Posts im Stil Grüne Hamburg zum Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit-mecklenburg-vorpommern',
    title: 'PM MV',
    description: 'Pressemitteilung im Stil Grüne Mecklenburg-Vorpommern',
    icon: PiWaves,
    avatar: '🌊',
    backgroundColor: '#316049',
    mention: 'presse-mv',
    contextPrefix: '[LV: Mecklenburg-Vorpommern / Modus: PM]',
    skillCategory: 'presse',
    promptTemplate: 'Schreibe eine Pressemitteilung im Stil Grüne MV zum Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit-mecklenburg-vorpommern',
    title: 'Social MV',
    description: 'Social-Media-Post im Stil Grüne Mecklenburg-Vorpommern',
    icon: PiWaves,
    avatar: '🌊',
    backgroundColor: '#316049',
    mention: 'social-mv',
    contextPrefix: '[LV: Mecklenburg-Vorpommern / Modus: Social Media]',
    skillCategory: 'social',
    promptTemplate: 'Erstelle Social-Media-Posts im Stil Grüne MV zum Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit-thueringen',
    title: 'PM Thüringen',
    description: 'Pressemitteilung im Stil Bündnisgrüne Thüringen',
    icon: PiTree,
    avatar: '🌲',
    backgroundColor: '#316049',
    mention: 'presse-thueringen',
    contextPrefix: '[LV: Thüringen / Modus: PM]',
    skillCategory: 'presse',
    promptTemplate: 'Schreibe eine Pressemitteilung im Stil Bündnisgrüne Thüringen zum Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit-thueringen',
    title: 'Social Thüringen',
    description: 'Social-Media-Post im Stil Bündnisgrüne Thüringen',
    icon: PiTree,
    avatar: '🌲',
    backgroundColor: '#316049',
    mention: 'social-thueringen',
    contextPrefix: '[LV: Thüringen / Modus: Social Media]',
    skillCategory: 'social',
    promptTemplate: 'Erstelle Social-Media-Posts im Stil Bündnisgrüne Thüringen zum Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit-brandenburg',
    title: 'PM Brandenburg',
    description: 'Pressemitteilung im Stil Brandenburger Bündnisgrüne',
    icon: PiFlowerLight,
    avatar: '🌻',
    backgroundColor: '#316049',
    mention: 'presse-brandenburg',
    contextPrefix: '[LV: Brandenburg / Modus: PM]',
    skillCategory: 'presse',
    promptTemplate: 'Schreibe eine Pressemitteilung im Stil Brandenburger Bündnisgrüne zum Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit-brandenburg',
    title: 'Social Brandenburg',
    description: 'Social-Media-Post im Stil Brandenburger Bündnisgrüne',
    icon: PiFlowerLight,
    avatar: '🌻',
    backgroundColor: '#316049',
    mention: 'social-brandenburg',
    contextPrefix: '[LV: Brandenburg / Modus: Social Media]',
    skillCategory: 'social',
    promptTemplate: 'Erstelle Social-Media-Posts im Stil Brandenburger Bündnisgrüne zum Thema: ',
  },
] as const satisfies readonly SystemSkill[];

const mentionMap = new Map<string, string>(
  SKILLS.map((skill) => [skill.mention.toLowerCase(), skill.identifier])
);

export function resolveSkillMention(alias: string): string | null {
  return mentionMap.get(alias.toLowerCase()) ?? null;
}
