import type { SystemAgentId } from './system.js';
import type { Skill } from './types.js';

type SystemSkill = Skill & { identifier: SystemAgentId };

export const SKILLS = [
  {
    identifier: 'gruenerator-antrag',
    title: 'Antrag',
    description: 'Anträge & Anfragen',
    avatar: '📝',
    backgroundColor: '#316049',
    mention: 'antrag',
    skillCategory: 'dokumente',
    isSystemDefault: true,
    promptTemplate: 'Schreibe einen Antrag zum Thema: ',
  },
  {
    identifier: 'gruenerator-buergerservice',
    title: 'Bürger*innenanfragen',
    description: 'Bürger*innenanfragen beantworten',
    avatar: '💬',
    backgroundColor: '#316049',
    mention: 'bürgerservice',
    skillCategory: 'presse',
    promptTemplate: 'Beantworte folgende Anfrage: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'Pressemitteilung',
    description: 'Pressemitteilungen verfassen',
    avatar: '📰',
    backgroundColor: '#316049',
    mention: 'presse',
    contextPrefix: '[Plattform: Pressemitteilung]',
    skillCategory: 'presse',
    isSystemDefault: true,
    promptTemplate: 'Schreibe eine PM zum Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'Instagram',
    description: 'Instagram-Posts & Captions',
    avatar: '📸',
    backgroundColor: '#E1306C',
    mention: 'instagram',
    contextPrefix: '[Plattform: Instagram]',
    skillCategory: 'social',
    isSystemDefault: true,
    promptTemplate: 'Post zu folgendem Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'Facebook',
    description: 'Facebook-Posts & Beiträge',
    avatar: '👍',
    backgroundColor: '#1877F2',
    mention: 'facebook',
    contextPrefix: '[Plattform: Facebook]',
    skillCategory: 'social',
    promptTemplate: 'Beitrag zu folgendem Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'Twitter / X',
    description: 'Tweets & Threads',
    avatar: '🐦',
    backgroundColor: '#1DA1F2',
    mention: 'twitter',
    contextPrefix: '[Plattform: Twitter]',
    skillCategory: 'social',
    promptTemplate: 'Tweet zu folgendem Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'LinkedIn',
    description: 'LinkedIn-Posts & Artikel',
    avatar: '💼',
    backgroundColor: '#0A66C2',
    mention: 'linkedin',
    contextPrefix: '[Plattform: LinkedIn]',
    skillCategory: 'social',
    promptTemplate: 'LinkedIn-Post zu: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'Reel / TikTok',
    description: 'Reel- & TikTok-Skripte',
    avatar: '🎬',
    backgroundColor: '#FE2C55',
    mention: 'reel',
    contextPrefix: '[Plattform: Reel/TikTok-Skript]',
    skillCategory: 'social',
    promptTemplate: 'Skript zu folgendem Thema: ',
  },
  {
    identifier: 'gruenerator-oeffentlichkeitsarbeit',
    title: 'Aktionsideen',
    description: 'Kreative Aktionsideen entwickeln',
    avatar: '💡',
    backgroundColor: '#F59E0B',
    mention: 'aktion',
    contextPrefix: '[Plattform: Aktionsideen]',
    skillCategory: 'sonstiges',
    promptTemplate: 'Entwickle Aktionsideen zu: ',
  },
  {
    identifier: 'gruenerator-rede-schreiber',
    title: 'Rede',
    description: 'Politische Reden',
    avatar: '🎙️',
    backgroundColor: '#316049',
    mention: 'rede',
    skillCategory: 'presse',
    promptTemplate: 'Schreibe eine Rede zum Thema: ',
  },
  {
    identifier: 'gruenerator-wahlprogramm',
    title: 'Wahlprogramm',
    description: 'Programmkapitel',
    avatar: '📋',
    backgroundColor: '#316049',
    mention: 'wahlprogramm',
    skillCategory: 'dokumente',
  },
  {
    identifier: 'gruenerator-leichte-sprache',
    title: 'Leichte Sprache',
    description: 'Texte in Leichte Sprache übersetzen',
    avatar: '🗣️',
    backgroundColor: '#316049',
    mention: 'leichte-sprache',
    skillCategory: 'sonstiges',
    promptTemplate: 'Übersetze folgenden Text in Leichte Sprache: ',
  },
] as const satisfies readonly SystemSkill[];

const mentionMap = new Map<string, string>(
  SKILLS.map((skill) => [skill.mention.toLowerCase(), skill.identifier])
);

export function resolveSkillMention(alias: string): string | null {
  return mentionMap.get(alias.toLowerCase()) ?? null;
}
