-- Maps chat sharepic variants to their lazily-minted canvas documents.
-- Written on first chat edit of a variant; `is_active` marks the variant the
-- chat's sharepic_edit intent targets when the request carries no explicit
-- currentSharepic selection. (variant_id is the UUID generated by
-- sharepicVariantHelpers when the variant was streamed to the client.)

CREATE TABLE IF NOT EXISTS chat_thread_canvases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id UUID NOT NULL,
  variant_id TEXT NOT NULL,
  canvas_id UUID NOT NULL REFERENCES collaborative_documents(id) ON DELETE CASCADE,
  canvas_type TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chat_thread_canvases_unique UNIQUE (thread_id, variant_id)
);

CREATE INDEX IF NOT EXISTS idx_chat_thread_canvases_thread
  ON chat_thread_canvases (thread_id);
