/**
 * Known RSS feed URLs for German and Austrian news sources.
 * Used by Monitor for article collection.
 * Verified 2026-03-19.
 */
export const KNOWN_RSS_FEEDS: Record<string, string> = {
  // German national
  'tagesschau.de': 'https://www.tagesschau.de/xml/rss2/',
  'zeit.de': 'https://newsfeed.zeit.de/index',
  'spiegel.de': 'https://www.spiegel.de/schlagzeilen/index.rss',
  'sueddeutsche.de': 'https://rss.sueddeutsche.de/alles',
  'faz.net': 'https://www.faz.net/rss/aktuell/',
  'taz.de': 'https://taz.de/!p4608;rss/',
  'welt.de': 'https://www.welt.de/feeds/latest.rss',
  'n-tv.de': 'https://www.n-tv.de/rss',
  'stern.de': 'https://www.stern.de/feed/standard/all/',
  'focus.de': 'https://www.focus.de/RSS/rss_intern.xml',
  't-online.de': 'https://feeds.t-online.de/rss/nachrichten',
  'handelsblatt.com': 'https://www.handelsblatt.com/contentexport/feed/schlagzeilen',
  'heise.de': 'https://www.heise.de/rss/heise-atom.xml',
  'tagesspiegel.de': 'https://www.tagesspiegel.de/contentexport/feed/berlin',
  'manager-magazin.de': 'https://www.manager-magazin.de/news/index.rss',
  'zdf.de': 'https://www.zdf.de/rss/zdf/nachrichten',
  'deutschlandfunk.de': 'https://www.deutschlandfunk.de/nachrichten-100.rss',
  'dw.com': 'https://rss.dw.com/rdf/rss-de-all',
  'wiwo.de': 'https://www.wiwo.de/contentexport/feed/rss/schlagzeilen',
  'telepolis.de': 'https://www.telepolis.de/news-atom.xml',
  'cicero.de': 'https://www.cicero.de/rss.xml',
  'jacobin.de': 'https://jacobin.de/rss',
  'bild.de': 'https://www.bild.de/rss-feeds/rss-16725492,feed=home.bild.html',
  'berliner-zeitung.de': 'https://www.berliner-zeitung.de/feed.xml',
  'sueddeutsche.de/politik': 'https://rss.sueddeutsche.de/rss/Politik',
  'sueddeutsche.de/wirtschaft': 'https://rss.sueddeutsche.de/rss/Wirtschaft',
  // German public broadcasters
  'ndr.de': 'https://www.ndr.de/home/index-rss.xml',
  'mdr.de': 'https://www.mdr.de/nachrichten/index-rss.xml',
  'br.de': 'https://nachrichtenfeeds.br.de/rss/nachrichten/seiten/QXAPkQJ',
  'wdr.de': 'https://www1.wdr.de/uebersicht-100.feed',
  'swr.de': 'https://www.swr.de/~rss/swraktuell-100.xml',
  'hessenschau.de': 'https://www.hessenschau.de/index.rss',
  'rbb24.de': 'https://www.rbb24.de/aktuell/index.xml/feed=rss.xml',
  // German regional
  'rp-online.de': 'https://rp-online.de/feed.rss',
  'merkur.de': 'https://www.merkur.de/welt/rssfeed.rdf',
  'fr.de': 'https://www.fr.de/rssfeed.rdf',
  'stuttgarter-zeitung.de': 'https://www.stuttgarter-zeitung.de/rss/topthemen.rss.feed',
  'augsburger-allgemeine.de': 'https://www.augsburger-allgemeine.de/rss',
  'hna.de': 'https://www.hna.de/welt/rssfeed.rdf',
  // Austrian
  'orf.at': 'https://rss.orf.at/news.xml',
  'derstandard.at': 'https://www.derstandard.at/rss',
  'diepresse.com': 'https://www.diepresse.com/rss',
  'kleinezeitung.at': 'https://www.kleinezeitung.at/rss/oesterreich',
  'nachrichten.at': 'https://www.nachrichten.at/storage/rss/rss/nachrichten.xml',
  'tt.com': 'https://www.tt.com/rss/news.xml',
  'news.at': 'https://www.news.at/rss/news',
  'meinbezirk.at': 'https://www.meinbezirk.at/rss',
  'noen.at': 'https://www.noen.at/xml/rss',
  'vienna.at': 'https://www.vienna.at/rss',
  'ots.at': 'https://www.ots.at/rss/index',
  'moment.at': 'https://www.moment.at/rss',
  'kontrast.at': 'https://kontrast.at/feed/',
  'exxpress.at': 'https://exxpress.at/feed/',
  'brandaktuell.at': 'https://www.brandaktuell.at/feed/',
  'krone.at': 'https://www.krone.at/nachrichten/rss.html',
  'kurier.at': 'https://kurier.at/xml/rss',
  'profil.at': 'https://www.profil.at/rss.xml',
  // European & specialized
  'euractiv.de': 'https://www.euractiv.de/feed/',
  'euronews.com': 'https://de.euronews.com/rss',
  'nzz.ch': 'https://www.nzz.ch/recent.rss',
  'correctiv.org': 'https://correctiv.org/feed/',
  'netzpolitik.org': 'https://netzpolitik.org/feed/',
  // Additional
  'saechsische.de': 'https://www.saechsische.de/arc/outboundfeeds/rss/',
  'ksta.de': 'https://feed.ksta.de/feed/rss/politik/index.rss',
  'rnd.de': 'https://www.rnd.de/arc/outboundfeeds/rss/',
  'tagesspiegel.de/politik': 'https://www.tagesspiegel.de/contentexport/feed/politik',
  'eurotopics.net': 'https://www.eurotopics.net/export/de/rss-debatten.xml',
  'gruene-bundestag.de/fachtexte': 'https://www.gruene-bundestag.de/fachtexte-rss-feed.xml',
  'gruene-bundestag.de/presse': 'https://www.gruene-bundestag.de/pressemitteilungen-rss-feed.xml',
};
