/**
 * Free Gophers Pack Illustration Definitions
 *
 * 153 CC0 gopher illustrations by Maria Letta
 * (https://github.com/MariaLetta/free-gophers-pack) — public domain.
 * Colorful illustrations rendered in their native colors.
 *
 * Generated from the SVG filenames — see apps/web/public/illustrations/gophers/.
 */

import type { SvgDef } from './types';

export const GOPHERS: SvgDef[] = [
  {
    id: 'gph-character-1',
    name: 'Gopher 1',
    filename: 'gopher-character-1.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-2',
    name: 'Gopher 2',
    filename: 'gopher-character-2.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-3',
    name: 'Gopher 3',
    filename: 'gopher-character-3.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-4',
    name: 'Gopher 4',
    filename: 'gopher-character-4.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-5',
    name: 'Gopher 5',
    filename: 'gopher-character-5.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-6',
    name: 'Gopher 6',
    filename: 'gopher-character-6.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-7',
    name: 'Gopher 7',
    filename: 'gopher-character-7.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-8',
    name: 'Gopher 8',
    filename: 'gopher-character-8.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-9',
    name: 'Gopher 9',
    filename: 'gopher-character-9.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-10',
    name: 'Gopher 10',
    filename: 'gopher-character-10.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-11',
    name: 'Gopher 11',
    filename: 'gopher-character-11.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-12',
    name: 'Gopher 12',
    filename: 'gopher-character-12.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-13',
    name: 'Gopher 13',
    filename: 'gopher-character-13.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-14',
    name: 'Gopher 14',
    filename: 'gopher-character-14.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-15',
    name: 'Gopher 15',
    filename: 'gopher-character-15.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-16',
    name: 'Gopher 16',
    filename: 'gopher-character-16.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-17',
    name: 'Gopher 17',
    filename: 'gopher-character-17.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-18',
    name: 'Gopher 18',
    filename: 'gopher-character-18.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-19',
    name: 'Gopher 19',
    filename: 'gopher-character-19.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-20',
    name: 'Gopher 20',
    filename: 'gopher-character-20.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-21',
    name: 'Gopher 21',
    filename: 'gopher-character-21.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-22',
    name: 'Gopher 22',
    filename: 'gopher-character-22.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-23',
    name: 'Gopher 23',
    filename: 'gopher-character-23.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-24',
    name: 'Gopher 24',
    filename: 'gopher-character-24.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-25',
    name: 'Gopher 25',
    filename: 'gopher-character-25.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-26',
    name: 'Gopher 26',
    filename: 'gopher-character-26.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-27',
    name: 'Gopher 27',
    filename: 'gopher-character-27.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-28',
    name: 'Gopher 28',
    filename: 'gopher-character-28.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-29',
    name: 'Gopher 29',
    filename: 'gopher-character-29.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-30',
    name: 'Gopher 30',
    filename: 'gopher-character-30.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-31',
    name: 'Gopher 31',
    filename: 'gopher-character-31.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-32',
    name: 'Gopher 32',
    filename: 'gopher-character-32.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-33',
    name: 'Gopher 33',
    filename: 'gopher-character-33.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-34',
    name: 'Gopher 34',
    filename: 'gopher-character-34.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-35',
    name: 'Gopher 35',
    filename: 'gopher-character-35.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-36',
    name: 'Gopher 36',
    filename: 'gopher-character-36.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-37',
    name: 'Gopher 37',
    filename: 'gopher-character-37.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-38',
    name: 'Gopher 38',
    filename: 'gopher-character-38.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-39',
    name: 'Gopher 39',
    filename: 'gopher-character-39.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-40',
    name: 'Gopher 40',
    filename: 'gopher-character-40.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-41',
    name: 'Gopher 41',
    filename: 'gopher-character-41.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-42',
    name: 'Gopher 42',
    filename: 'gopher-character-42.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-43',
    name: 'Gopher 43',
    filename: 'gopher-character-43.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-44',
    name: 'Gopher 44',
    filename: 'gopher-character-44.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-45',
    name: 'Gopher 45',
    filename: 'gopher-character-45.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-46',
    name: 'Gopher 46',
    filename: 'gopher-character-46.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-47',
    name: 'Gopher 47',
    filename: 'gopher-character-47.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-48',
    name: 'Gopher 48',
    filename: 'gopher-character-48.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-49',
    name: 'Gopher 49',
    filename: 'gopher-character-49.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-50',
    name: 'Gopher 50',
    filename: 'gopher-character-50.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-51',
    name: 'Gopher 51',
    filename: 'gopher-character-51.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-52',
    name: 'Gopher 52',
    filename: 'gopher-character-52.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-53',
    name: 'Gopher 53',
    filename: 'gopher-character-53.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-54',
    name: 'Gopher 54',
    filename: 'gopher-character-54.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-55',
    name: 'Gopher 55',
    filename: 'gopher-character-55.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-56',
    name: 'Gopher 56',
    filename: 'gopher-character-56.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-57',
    name: 'Gopher 57',
    filename: 'gopher-character-57.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-58',
    name: 'Gopher 58',
    filename: 'gopher-character-58.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-59',
    name: 'Gopher 59',
    filename: 'gopher-character-59.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-60',
    name: 'Gopher 60',
    filename: 'gopher-character-60.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-61',
    name: 'Gopher 61',
    filename: 'gopher-character-61.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-62',
    name: 'Gopher 62',
    filename: 'gopher-character-62.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-63',
    name: 'Gopher 63',
    filename: 'gopher-character-63.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-64',
    name: 'Gopher 64',
    filename: 'gopher-character-64.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-65',
    name: 'Gopher 65',
    filename: 'gopher-character-65.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-66',
    name: 'Gopher 66',
    filename: 'gopher-character-66.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-67',
    name: 'Gopher 67',
    filename: 'gopher-character-67.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-68',
    name: 'Gopher 68',
    filename: 'gopher-character-68.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-69',
    name: 'Gopher 69',
    filename: 'gopher-character-69.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-70',
    name: 'Gopher 70',
    filename: 'gopher-character-70.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-71',
    name: 'Gopher 71',
    filename: 'gopher-character-71.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-72',
    name: 'Gopher 72',
    filename: 'gopher-character-72.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-73',
    name: 'Gopher 73',
    filename: 'gopher-character-73.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-74',
    name: 'Gopher 74',
    filename: 'gopher-character-74.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-75',
    name: 'Gopher 75',
    filename: 'gopher-character-75.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-76',
    name: 'Gopher 76',
    filename: 'gopher-character-76.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-77',
    name: 'Gopher 77',
    filename: 'gopher-character-77.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-character-78',
    name: 'Gopher 78',
    filename: 'gopher-character-78.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'figur', 'charakter', 'maskottchen'],
    category: 'Gopher',
  },
  {
    id: 'gph-christmas-1',
    name: 'Gopher Weihnachten 1',
    filename: 'gopher-christmas-1.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'weihnachten', 'christmas', 'winter'],
    category: 'Gopher',
  },
  {
    id: 'gph-christmas-2',
    name: 'Gopher Weihnachten 2',
    filename: 'gopher-christmas-2.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'weihnachten', 'christmas', 'winter'],
    category: 'Gopher',
  },
  {
    id: 'gph-christmas-3',
    name: 'Gopher Weihnachten 3',
    filename: 'gopher-christmas-3.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'weihnachten', 'christmas', 'winter'],
    category: 'Gopher',
  },
  {
    id: 'gph-christmas-4',
    name: 'Gopher Weihnachten 4',
    filename: 'gopher-christmas-4.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'weihnachten', 'christmas', 'winter'],
    category: 'Gopher',
  },
  {
    id: 'gph-christmas-5',
    name: 'Gopher Weihnachten 5',
    filename: 'gopher-christmas-5.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'weihnachten', 'christmas', 'winter'],
    category: 'Gopher',
  },
  {
    id: 'gph-christmas-6',
    name: 'Gopher Weihnachten 6',
    filename: 'gopher-christmas-6.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'weihnachten', 'christmas', 'winter'],
    category: 'Gopher',
  },
  {
    id: 'gph-christmas-7',
    name: 'Gopher Weihnachten 7',
    filename: 'gopher-christmas-7.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'weihnachten', 'christmas', 'winter'],
    category: 'Gopher',
  },
  {
    id: 'gph-christmas-8',
    name: 'Gopher Weihnachten 8',
    filename: 'gopher-christmas-8.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'weihnachten', 'christmas', 'winter'],
    category: 'Gopher',
  },
  {
    id: 'gph-christmas-9',
    name: 'Gopher Weihnachten 9',
    filename: 'gopher-christmas-9.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'weihnachten', 'christmas', 'winter'],
    category: 'Gopher',
  },
  {
    id: 'gph-christmas-10',
    name: 'Gopher Weihnachten 10',
    filename: 'gopher-christmas-10.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'weihnachten', 'christmas', 'winter'],
    category: 'Gopher',
  },
  {
    id: 'gph-christmas-11',
    name: 'Gopher Weihnachten 11',
    filename: 'gopher-christmas-11.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'weihnachten', 'christmas', 'winter'],
    category: 'Gopher',
  },
  {
    id: 'gph-christmas-12',
    name: 'Gopher Weihnachten 12',
    filename: 'gopher-christmas-12.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'weihnachten', 'christmas', 'winter'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-1',
    name: 'Gopher Goroutine 1',
    filename: 'gopher-goroutine-1.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-2',
    name: 'Gopher Goroutine 2',
    filename: 'gopher-goroutine-2.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-3',
    name: 'Gopher Goroutine 3',
    filename: 'gopher-goroutine-3.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-4',
    name: 'Gopher Goroutine 4',
    filename: 'gopher-goroutine-4.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-5',
    name: 'Gopher Goroutine 5',
    filename: 'gopher-goroutine-5.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-6',
    name: 'Gopher Goroutine 6',
    filename: 'gopher-goroutine-6.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-7',
    name: 'Gopher Goroutine 7',
    filename: 'gopher-goroutine-7.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-8',
    name: 'Gopher Goroutine 8',
    filename: 'gopher-goroutine-8.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-9',
    name: 'Gopher Goroutine 9',
    filename: 'gopher-goroutine-9.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-10',
    name: 'Gopher Goroutine 10',
    filename: 'gopher-goroutine-10.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-11',
    name: 'Gopher Goroutine 11',
    filename: 'gopher-goroutine-11.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-12',
    name: 'Gopher Goroutine 12',
    filename: 'gopher-goroutine-12.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-13',
    name: 'Gopher Goroutine 13',
    filename: 'gopher-goroutine-13.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-14',
    name: 'Gopher Goroutine 14',
    filename: 'gopher-goroutine-14.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-15',
    name: 'Gopher Goroutine 15',
    filename: 'gopher-goroutine-15.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-16',
    name: 'Gopher Goroutine 16',
    filename: 'gopher-goroutine-16.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-goroutine-17',
    name: 'Gopher Goroutine 17',
    filename: 'gopher-goroutine-17.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'goroutine', 'nebenlaeufig'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-1',
    name: 'Gopher Szene 1',
    filename: 'gopher-illustration-1.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-2',
    name: 'Gopher Szene 2',
    filename: 'gopher-illustration-2.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-3',
    name: 'Gopher Szene 3',
    filename: 'gopher-illustration-3.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-4',
    name: 'Gopher Szene 4',
    filename: 'gopher-illustration-4.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-5',
    name: 'Gopher Szene 5',
    filename: 'gopher-illustration-5.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-6',
    name: 'Gopher Szene 6',
    filename: 'gopher-illustration-6.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-7',
    name: 'Gopher Szene 7',
    filename: 'gopher-illustration-7.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-8',
    name: 'Gopher Szene 8',
    filename: 'gopher-illustration-8.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-9',
    name: 'Gopher Szene 9',
    filename: 'gopher-illustration-9.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-10',
    name: 'Gopher Szene 10',
    filename: 'gopher-illustration-10.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-11',
    name: 'Gopher Szene 11',
    filename: 'gopher-illustration-11.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-12',
    name: 'Gopher Szene 12',
    filename: 'gopher-illustration-12.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-13',
    name: 'Gopher Szene 13',
    filename: 'gopher-illustration-13.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-14',
    name: 'Gopher Szene 14',
    filename: 'gopher-illustration-14.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-15',
    name: 'Gopher Szene 15',
    filename: 'gopher-illustration-15.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-16',
    name: 'Gopher Szene 16',
    filename: 'gopher-illustration-16.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-17',
    name: 'Gopher Szene 17',
    filename: 'gopher-illustration-17.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-18',
    name: 'Gopher Szene 18',
    filename: 'gopher-illustration-18.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-19',
    name: 'Gopher Szene 19',
    filename: 'gopher-illustration-19.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-20',
    name: 'Gopher Szene 20',
    filename: 'gopher-illustration-20.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-21',
    name: 'Gopher Szene 21',
    filename: 'gopher-illustration-21.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-22',
    name: 'Gopher Szene 22',
    filename: 'gopher-illustration-22.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-23',
    name: 'Gopher Szene 23',
    filename: 'gopher-illustration-23.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-24',
    name: 'Gopher Szene 24',
    filename: 'gopher-illustration-24.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-25',
    name: 'Gopher Szene 25',
    filename: 'gopher-illustration-25.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-26',
    name: 'Gopher Szene 26',
    filename: 'gopher-illustration-26.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-27',
    name: 'Gopher Szene 27',
    filename: 'gopher-illustration-27.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-28',
    name: 'Gopher Szene 28',
    filename: 'gopher-illustration-28.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-29',
    name: 'Gopher Szene 29',
    filename: 'gopher-illustration-29.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-30',
    name: 'Gopher Szene 30',
    filename: 'gopher-illustration-30.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-31',
    name: 'Gopher Szene 31',
    filename: 'gopher-illustration-31.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-32',
    name: 'Gopher Szene 32',
    filename: 'gopher-illustration-32.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-33',
    name: 'Gopher Szene 33',
    filename: 'gopher-illustration-33.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-34',
    name: 'Gopher Szene 34',
    filename: 'gopher-illustration-34.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-35',
    name: 'Gopher Szene 35',
    filename: 'gopher-illustration-35.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-36',
    name: 'Gopher Szene 36',
    filename: 'gopher-illustration-36.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-37',
    name: 'Gopher Szene 37',
    filename: 'gopher-illustration-37.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-38',
    name: 'Gopher Szene 38',
    filename: 'gopher-illustration-38.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-39',
    name: 'Gopher Szene 39',
    filename: 'gopher-illustration-39.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-40',
    name: 'Gopher Szene 40',
    filename: 'gopher-illustration-40.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-41',
    name: 'Gopher Szene 41',
    filename: 'gopher-illustration-41.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-42',
    name: 'Gopher Szene 42',
    filename: 'gopher-illustration-42.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-43',
    name: 'Gopher Szene 43',
    filename: 'gopher-illustration-43.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-44',
    name: 'Gopher Szene 44',
    filename: 'gopher-illustration-44.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-45',
    name: 'Gopher Szene 45',
    filename: 'gopher-illustration-45.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
  {
    id: 'gph-illustration-46',
    name: 'Gopher Szene 46',
    filename: 'gopher-illustration-46.svg',
    source: 'gophers',
    tags: ['gopher', 'go', 'golang', 'szene', 'illustration'],
    category: 'Gopher',
  },
];
