/**
 * Humaaans Illustration Definitions
 *
 * 32 people figures by Pablo Stanley (https://humaaans.com/),
 * free for personal and commercial use. Rendered in native colors.
 */

import type { SvgDef } from './types';

export const HUMAAANS: SvgDef[] = [
  {
    id: 'hm-sitting-1',
    name: 'Sitzend 1',
    filename: 'sitting-1.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'hm-sitting-2',
    name: 'Sitzend 2',
    filename: 'sitting-2.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'hm-sitting-3',
    name: 'Sitzend 3',
    filename: 'sitting-3.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'hm-sitting-4',
    name: 'Sitzend 4',
    filename: 'sitting-4.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'hm-sitting-5',
    name: 'Sitzend 5',
    filename: 'sitting-5.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'hm-sitting-6',
    name: 'Sitzend 6',
    filename: 'sitting-6.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'hm-sitting-7',
    name: 'Sitzend 7',
    filename: 'sitting-7.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'hm-sitting-8',
    name: 'Sitzend 8',
    filename: 'sitting-8.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-1',
    name: 'Stehend 1',
    filename: 'standing-1.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-2',
    name: 'Stehend 2',
    filename: 'standing-2.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-3',
    name: 'Stehend 3',
    filename: 'standing-3.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-4',
    name: 'Stehend 4',
    filename: 'standing-4.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-5',
    name: 'Stehend 5',
    filename: 'standing-5.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-6',
    name: 'Stehend 6',
    filename: 'standing-6.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-7',
    name: 'Stehend 7',
    filename: 'standing-7.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-8',
    name: 'Stehend 8',
    filename: 'standing-8.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-9',
    name: 'Stehend 9',
    filename: 'standing-9.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-10',
    name: 'Stehend 10',
    filename: 'standing-10.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-11',
    name: 'Stehend 11',
    filename: 'standing-11.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-12',
    name: 'Stehend 12',
    filename: 'standing-12.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-13',
    name: 'Stehend 13',
    filename: 'standing-13.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-14',
    name: 'Stehend 14',
    filename: 'standing-14.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-15',
    name: 'Stehend 15',
    filename: 'standing-15.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-16',
    name: 'Stehend 16',
    filename: 'standing-16.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-17',
    name: 'Stehend 17',
    filename: 'standing-17.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-18',
    name: 'Stehend 18',
    filename: 'standing-18.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-19',
    name: 'Stehend 19',
    filename: 'standing-19.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-20',
    name: 'Stehend 20',
    filename: 'standing-20.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-21',
    name: 'Stehend 21',
    filename: 'standing-21.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-22',
    name: 'Stehend 22',
    filename: 'standing-22.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-23',
    name: 'Stehend 23',
    filename: 'standing-23.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'hm-standing-24',
    name: 'Stehend 24',
    filename: 'standing-24.svg',
    source: 'humaaans',
    tags: ['person', 'mensch', 'figur', 'stehend'],
    category: 'Menschen',
  },
];
