/**
 * illlustrations.co Illustration Definitions
 *
 * 131 open-source SVG illustrations by Vijay Verma (MIT license,
 * https://illlustrations.co/). Colorful multi-tone illustrations rendered in
 * their native colors (not recolored by the swatch picker).
 *
 * Generated from the SVG filenames — see apps/web/public/illustrations/illlustrations/.
 */

import type { SvgDef } from './types';

export const ILLLUSTRATIONS: SvgDef[] = [
  {
    id: 'il-101-gym-guy',
    name: 'Gym Guy',
    filename: '101-gym-guy.svg',
    source: 'illlustrations',
    tags: ['gym', 'guy'],
  },
  {
    id: 'il-102-gym-cycle',
    name: 'Gym Cycle',
    filename: '102-gym-cycle.svg',
    source: 'illlustrations',
    tags: ['gym', 'cycle'],
  },
  {
    id: 'il-103-gym-time',
    name: 'Gym Time',
    filename: '103-gym-time.svg',
    source: 'illlustrations',
    tags: ['gym', 'time'],
  },
  {
    id: 'il-104-dumbbell',
    name: 'Dumbbell',
    filename: '104-dumbbell.svg',
    source: 'illlustrations',
    tags: ['dumbbell'],
  },
  {
    id: 'il-105-freelancer',
    name: 'Freelancer',
    filename: '105-freelancer.svg',
    source: 'illlustrations',
    tags: ['freelancer'],
  },
  {
    id: 'il-106-italy',
    name: 'Italy',
    filename: '106-italy.svg',
    source: 'illlustrations',
    tags: ['italy'],
  },
  {
    id: 'il-107-healthy',
    name: 'Healthy',
    filename: '107-healthy.svg',
    source: 'illlustrations',
    tags: ['healthy'],
  },
  {
    id: 'il-108-forget-password',
    name: 'Forget Password',
    filename: '108-forget-password.svg',
    source: 'illlustrations',
    tags: ['forget', 'password'],
  },
  {
    id: 'il-109-map-location',
    name: 'Map Location',
    filename: '109-map-location.svg',
    source: 'illlustrations',
    tags: ['map', 'location'],
  },
  {
    id: 'il-110-sega-megdrive',
    name: 'Sega Megdrive',
    filename: '110-sega-megdrive.svg',
    source: 'illlustrations',
    tags: ['sega', 'megdrive'],
  },
  {
    id: 'il-111-coding',
    name: 'Coding',
    filename: '111-coding.svg',
    source: 'illlustrations',
    tags: ['coding'],
  },
  {
    id: 'il-112-installing',
    name: 'Installing',
    filename: '112-installing.svg',
    source: 'illlustrations',
    tags: ['installing'],
  },
  {
    id: 'il-113-workstation',
    name: 'Workstation',
    filename: '113-workstation.svg',
    source: 'illlustrations',
    tags: ['workstation'],
  },
  {
    id: 'il-114-retro-tv',
    name: 'Retro Tv',
    filename: '114-retro-tv.svg',
    source: 'illlustrations',
    tags: ['retro', 'tv'],
  },
  {
    id: 'il-115-eiffel-tower',
    name: 'Eiffel Tower',
    filename: '115-eiffel-tower.svg',
    source: 'illlustrations',
    tags: ['eiffel', 'tower'],
  },
  {
    id: 'il-116-gameboy',
    name: 'Gameboy',
    filename: '116-gameboy.svg',
    source: 'illlustrations',
    tags: ['gameboy'],
  },
  {
    id: 'il-117-ironman',
    name: 'Ironman',
    filename: '117-ironman.svg',
    source: 'illlustrations',
    tags: ['ironman'],
  },
  {
    id: 'il-118-macbook',
    name: 'Macbook',
    filename: '118-macbook.svg',
    source: 'illlustrations',
    tags: ['macbook'],
  },
  {
    id: 'il-119-working',
    name: 'Working',
    filename: '119-working.svg',
    source: 'illlustrations',
    tags: ['working'],
  },
  {
    id: 'il-120-power-of-pen',
    name: 'Power Of Pen',
    filename: '120-power-of-pen.svg',
    source: 'illlustrations',
    tags: ['power', 'of', 'pen'],
  },
  {
    id: 'il-121-work-from-home-1',
    name: 'Work From Home 1',
    filename: '121-work-from-home-1.svg',
    source: 'illlustrations',
    tags: ['work', 'from', 'home', '1'],
  },
  {
    id: 'il-122-work-from-home-2',
    name: 'Work From Home 2',
    filename: '122-work-from-home-2.svg',
    source: 'illlustrations',
    tags: ['work', 'from', 'home', '2'],
  },
  {
    id: 'il-123-temprature-meter',
    name: 'Temprature Meter',
    filename: '123-temprature-meter.svg',
    source: 'illlustrations',
    tags: ['temprature', 'meter'],
  },
  {
    id: 'il-124-sanitizer',
    name: 'Sanitizer',
    filename: '124-sanitizer.svg',
    source: 'illlustrations',
    tags: ['sanitizer'],
  },
  {
    id: 'il-125-wash-hand',
    name: 'Wash Hand',
    filename: '125-wash-hand.svg',
    source: 'illlustrations',
    tags: ['wash', 'hand'],
  },
  {
    id: 'il-126-namaste-no-hand-shake',
    name: 'Namaste No Hand Shake',
    filename: '126-namaste-no-hand-shake.svg',
    source: 'illlustrations',
    tags: ['namaste', 'no', 'hand', 'shake'],
  },
  {
    id: 'il-127-sick-sneezing',
    name: 'Sick Sneezing',
    filename: '127-sick-sneezing.svg',
    source: 'illlustrations',
    tags: ['sick', 'sneezing'],
  },
  {
    id: 'il-128-forehead-tester',
    name: 'Forehead Tester',
    filename: '128-forehead-tester.svg',
    source: 'illlustrations',
    tags: ['forehead', 'tester'],
  },
  {
    id: 'il-129-wear-mask',
    name: 'Wear Mask',
    filename: '129-wear-mask.svg',
    source: 'illlustrations',
    tags: ['wear', 'mask'],
  },
  {
    id: 'il-130-covid-virus',
    name: 'COVID Virus',
    filename: '130-COVID-Virus.svg',
    source: 'illlustrations',
    tags: ['covid', 'virus'],
  },
  {
    id: 'il-day1-ipod',
    name: 'Ipod',
    filename: 'day1-ipod.svg',
    source: 'illlustrations',
    tags: ['ipod'],
  },
  {
    id: 'il-day2-gaming-console',
    name: 'Gaming Console',
    filename: 'day2-gaming-console.svg',
    source: 'illlustrations',
    tags: ['gaming', 'console'],
  },
  {
    id: 'il-day3-gaming-mouse',
    name: 'Gaming Mouse',
    filename: 'day3-gaming-mouse.svg',
    source: 'illlustrations',
    tags: ['gaming', 'mouse'],
  },
  {
    id: 'il-day4-polariod',
    name: 'Polariod',
    filename: 'day4-polariod.svg',
    source: 'illlustrations',
    tags: ['polariod'],
  },
  {
    id: 'il-day5-vault',
    name: 'Vault',
    filename: 'day5-vault.svg',
    source: 'illlustrations',
    tags: ['vault'],
  },
  {
    id: 'il-day6-open-vault',
    name: 'Open Vault',
    filename: 'day6-open-vault.svg',
    source: 'illlustrations',
    tags: ['open', 'vault'],
  },
  {
    id: 'il-day7-vintage-camera',
    name: 'Vintage Camera',
    filename: 'day7-vintage-camera.svg',
    source: 'illlustrations',
    tags: ['vintage', 'camera'],
  },
  {
    id: 'il-day8-printer',
    name: 'Printer',
    filename: 'day8-printer.svg',
    source: 'illlustrations',
    tags: ['printer'],
  },
  {
    id: 'il-day9-toolbox',
    name: 'Toolbox',
    filename: 'day9-toolbox.svg',
    source: 'illlustrations',
    tags: ['toolbox'],
  },
  {
    id: 'il-day10-canvas-stand',
    name: 'Canvas Stand',
    filename: 'day10-canvas-stand.svg',
    source: 'illlustrations',
    tags: ['canvas', 'stand'],
  },
  {
    id: 'il-day11-blackboard',
    name: 'Blackboard',
    filename: 'day11-blackboard.svg',
    source: 'illlustrations',
    tags: ['blackboard'],
  },
  {
    id: 'il-day12-bed',
    name: 'Bed',
    filename: 'day12-bed.svg',
    source: 'illlustrations',
    tags: ['bed'],
  },
  {
    id: 'il-day13-it-girl',
    name: 'It Girl',
    filename: 'day13-it-girl.svg',
    source: 'illlustrations',
    tags: ['it', 'girl'],
  },
  {
    id: 'il-day14-forklift',
    name: 'Forklift',
    filename: 'day14-forklift.svg',
    source: 'illlustrations',
    tags: ['forklift'],
  },
  {
    id: 'il-day15-color-tool',
    name: 'Color Tool',
    filename: 'day15-color-tool.svg',
    source: 'illlustrations',
    tags: ['color', 'tool'],
  },
  {
    id: 'il-day16-retro-cassette',
    name: 'Retro Cassette',
    filename: 'day16-retro-cassette.svg',
    source: 'illlustrations',
    tags: ['retro', 'cassette'],
  },
  {
    id: 'il-day17-walkie-talkie',
    name: 'Walkie Talkie',
    filename: 'day17-walkie-talkie.svg',
    source: 'illlustrations',
    tags: ['walkie', 'talkie'],
  },
  {
    id: 'il-day18-floppy',
    name: 'Floppy',
    filename: 'day18-floppy.svg',
    source: 'illlustrations',
    tags: ['floppy'],
  },
  {
    id: 'il-day19-apple-watch',
    name: 'Apple Watch',
    filename: 'day19-apple-watch.svg',
    source: 'illlustrations',
    tags: ['apple', 'watch'],
  },
  {
    id: 'il-day20-rocket',
    name: 'Rocket',
    filename: 'day20-rocket.svg',
    source: 'illlustrations',
    tags: ['rocket'],
  },
  {
    id: 'il-day21-lantern',
    name: 'Lantern',
    filename: 'day21-Lantern.svg',
    source: 'illlustrations',
    tags: ['lantern'],
  },
  {
    id: 'il-day22-owl',
    name: 'Owl',
    filename: 'day22-owl.svg',
    source: 'illlustrations',
    tags: ['owl'],
  },
  {
    id: 'il-day23-radio',
    name: 'Radio',
    filename: 'day23-radio.svg',
    source: 'illlustrations',
    tags: ['radio'],
  },
  {
    id: 'il-day24-e-scooter',
    name: 'E Scooter',
    filename: 'day24-e-scooter.svg',
    source: 'illlustrations',
    tags: ['e', 'scooter'],
  },
  {
    id: 'il-day25-sport-bicycle',
    name: 'Sport Bicycle',
    filename: 'day25-sport-bicycle.svg',
    source: 'illlustrations',
    tags: ['sport', 'bicycle'],
  },
  {
    id: 'il-day26-rainbow',
    name: 'Rainbow',
    filename: 'day26-rainbow.svg',
    source: 'illlustrations',
    tags: ['rainbow'],
  },
  {
    id: 'il-day27-my-robot',
    name: 'My Robot',
    filename: 'day27-my-robot.svg',
    source: 'illlustrations',
    tags: ['my', 'robot'],
  },
  {
    id: 'il-day28-selfi-girl',
    name: 'Selfi Girl',
    filename: 'day28-selfi-girl.svg',
    source: 'illlustrations',
    tags: ['selfi', 'girl'],
  },
  {
    id: 'il-day29-selfie-boy',
    name: 'Selfie Boy',
    filename: 'day29-selfie-boy.svg',
    source: 'illlustrations',
    tags: ['selfie', 'boy'],
  },
  {
    id: 'il-day30-cafe',
    name: 'Cafe',
    filename: 'day30-cafe.svg',
    source: 'illlustrations',
    tags: ['cafe'],
  },
  {
    id: 'il-day31-sweet-home',
    name: 'Sweet Home',
    filename: 'day31-sweet-home.svg',
    source: 'illlustrations',
    tags: ['sweet', 'home'],
  },
  {
    id: 'il-day32-frankenstein',
    name: 'Frankenstein',
    filename: 'day32-frankenstein.svg',
    source: 'illlustrations',
    tags: ['frankenstein'],
  },
  {
    id: 'il-day33-pumpkin',
    name: 'Pumpkin',
    filename: 'day33-pumpkin.svg',
    source: 'illlustrations',
    tags: ['pumpkin'],
  },
  {
    id: 'il-day34-ticket',
    name: 'Ticket',
    filename: 'day34-ticket.svg',
    source: 'illlustrations',
    tags: ['ticket'],
  },
  {
    id: 'il-day35-firework',
    name: 'Firework',
    filename: 'day35-firework.svg',
    source: 'illlustrations',
    tags: ['firework'],
  },
  {
    id: 'il-day36-abacus',
    name: 'Abacus',
    filename: 'day36-abacus.svg',
    source: 'illlustrations',
    tags: ['abacus'],
  },
  {
    id: 'il-day37-calculator',
    name: 'Calculator',
    filename: 'day37-calculator.svg',
    source: 'illlustrations',
    tags: ['calculator'],
  },
  {
    id: 'il-day38-macintosh',
    name: 'Macintosh',
    filename: 'day38-macintosh.svg',
    source: 'illlustrations',
    tags: ['macintosh'],
  },
  {
    id: 'il-day39-pc',
    name: 'Pc',
    filename: 'day39-pc.svg',
    source: 'illlustrations',
    tags: ['pc'],
  },
  {
    id: 'il-day40-powerbook-100',
    name: 'Powerbook 100',
    filename: 'day40-powerbook-100.svg',
    source: 'illlustrations',
    tags: ['powerbook', '100'],
  },
  {
    id: 'il-day41-desktop',
    name: 'Desktop',
    filename: 'day41-desktop.svg',
    source: 'illlustrations',
    tags: ['desktop'],
  },
  {
    id: 'il-day42-imac',
    name: 'Imac',
    filename: 'day42-imac.svg',
    source: 'illlustrations',
    tags: ['imac'],
  },
  {
    id: 'il-day43-ram',
    name: 'Ram',
    filename: 'day43-ram.svg',
    source: 'illlustrations',
    tags: ['ram'],
  },
  {
    id: 'il-day44-hdd',
    name: 'Hdd',
    filename: 'day44-hdd.svg',
    source: 'illlustrations',
    tags: ['hdd'],
  },
  {
    id: 'il-day45-gpu-ati',
    name: 'Gpu Ati',
    filename: 'day45-gpu-ati.svg',
    source: 'illlustrations',
    tags: ['gpu', 'ati'],
  },
  {
    id: 'il-day46-experiment-lab',
    name: 'Experiment Lab',
    filename: 'day46-experiment-lab.svg',
    source: 'illlustrations',
    tags: ['experiment', 'lab'],
  },
  {
    id: 'il-day46-medical-lab',
    name: 'Medical Lab',
    filename: 'day46-medical-lab.svg',
    source: 'illlustrations',
    tags: ['medical', 'lab'],
  },
  {
    id: 'il-day47-chemistry-lab',
    name: 'Chemistry Lab',
    filename: 'day47-chemistry-lab.svg',
    source: 'illlustrations',
    tags: ['chemistry', 'lab'],
  },
  {
    id: 'il-day48-medical-lab',
    name: 'Medical Lab',
    filename: 'day48-medical-lab.svg',
    source: 'illlustrations',
    tags: ['medical', 'lab'],
  },
  {
    id: 'il-day49-angler-fish',
    name: 'Angler Fish',
    filename: 'day49-angler-fish.svg',
    source: 'illlustrations',
    tags: ['angler', 'fish'],
  },
  {
    id: 'il-day50-pirahna',
    name: 'Pirahna',
    filename: 'day50-pirahna.svg',
    source: 'illlustrations',
    tags: ['pirahna'],
  },
  {
    id: 'il-day51-whale',
    name: 'Whale',
    filename: 'day51-whale.svg',
    source: 'illlustrations',
    tags: ['whale'],
  },
  {
    id: 'il-day52-auntum',
    name: 'Auntum',
    filename: 'day52-auntum.svg',
    source: 'illlustrations',
    tags: ['auntum'],
  },
  {
    id: 'il-day53-farm',
    name: 'Farm',
    filename: 'day53-farm.svg',
    source: 'illlustrations',
    tags: ['farm'],
  },
  {
    id: 'il-day54-building',
    name: 'Building',
    filename: 'day54-building.svg',
    source: 'illlustrations',
    tags: ['building'],
  },
  {
    id: 'il-day55-living-room-interior',
    name: 'Living Room Interior',
    filename: 'day55-living-room-interior.svg',
    source: 'illlustrations',
    tags: ['living', 'room', 'interior'],
  },
  {
    id: 'il-day56-tv-room',
    name: 'Tv Room',
    filename: 'day56-tv-room.svg',
    source: 'illlustrations',
    tags: ['tv', 'room'],
  },
  {
    id: 'il-day57-reading-room',
    name: 'Reading Room',
    filename: 'day57-reading-room.svg',
    source: 'illlustrations',
    tags: ['reading', 'room'],
  },
  {
    id: 'il-day58-bedroom',
    name: 'Bedroom',
    filename: 'day58-bedroom.svg',
    source: 'illlustrations',
    tags: ['bedroom'],
  },
  {
    id: 'il-day59-kitchen',
    name: 'Kitchen',
    filename: 'day59-kitchen.svg',
    source: 'illlustrations',
    tags: ['kitchen'],
  },
  {
    id: 'il-day60-bathroom',
    name: 'Bathroom',
    filename: 'day60-bathroom.svg',
    source: 'illlustrations',
    tags: ['bathroom'],
  },
  {
    id: 'il-day61-travel-bag',
    name: 'Travel Bag',
    filename: 'day61-travel-bag.svg',
    source: 'illlustrations',
    tags: ['travel', 'bag'],
  },
  {
    id: 'il-day62-office-bag',
    name: 'Office Bag',
    filename: 'day62-office-bag.svg',
    source: 'illlustrations',
    tags: ['office', 'bag'],
  },
  {
    id: 'il-day63-school-bag',
    name: 'School Bag',
    filename: 'day63-school-bag.svg',
    source: 'illlustrations',
    tags: ['school', 'bag'],
  },
  {
    id: 'il-day64-followers',
    name: 'Followers',
    filename: 'day64-followers.svg',
    source: 'illlustrations',
    tags: ['followers'],
  },
  {
    id: 'il-day65-city-road',
    name: 'City Road',
    filename: 'day65-city-road.svg',
    source: 'illlustrations',
    tags: ['city', 'road'],
  },
  {
    id: 'il-day66-travel',
    name: 'Travel',
    filename: 'day66-travel.svg',
    source: 'illlustrations',
    tags: ['travel'],
  },
  {
    id: 'il-day67-dog',
    name: 'Dog',
    filename: 'day67-dog.svg',
    source: 'illlustrations',
    tags: ['dog'],
  },
  {
    id: 'il-day68-happy-cat',
    name: 'Happy Cat',
    filename: 'day68-happy-cat.svg',
    source: 'illlustrations',
    tags: ['happy', 'cat'],
  },
  {
    id: 'il-day69-dotted-notebook',
    name: 'Dotted Notebook',
    filename: 'day69-dotted-notebook.svg',
    source: 'illlustrations',
    tags: ['dotted', 'notebook'],
  },
  {
    id: 'il-day70-designer-fav-tool-wacom',
    name: 'Designer Fav Tool Wacom',
    filename: 'day70-designer-fav-tool-wacom.svg',
    source: 'illlustrations',
    tags: ['designer', 'fav', 'tool', 'wacom'],
  },
  {
    id: 'il-day71-designer-tool-essential',
    name: 'Designer Tool Essential',
    filename: 'day71-designer-tool-essential.svg',
    source: 'illlustrations',
    tags: ['designer', 'tool', 'essential'],
  },
  {
    id: 'il-day72-designer-tool-war',
    name: 'Designer Tool War',
    filename: 'day72-designer-tool-war.svg',
    source: 'illlustrations',
    tags: ['designer', 'tool', 'war'],
  },
  {
    id: 'il-day73-writing-tool',
    name: 'Writing Tool',
    filename: 'day73-writing-tool.svg',
    source: 'illlustrations',
    tags: ['writing', 'tool'],
  },
  {
    id: 'il-day74-stationary-set',
    name: 'Stationary Set',
    filename: 'day74-stationary-set.svg',
    source: 'illlustrations',
    tags: ['stationary', 'set'],
  },
  {
    id: 'il-day75-stationary-set-2',
    name: 'Stationary Set 2',
    filename: 'day75-stationary-set-2.svg',
    source: 'illlustrations',
    tags: ['stationary', 'set', '2'],
  },
  {
    id: 'il-day76-watch-spectacle',
    name: 'Watch Spectacle',
    filename: 'day76-watch-spectacle.svg',
    source: 'illlustrations',
    tags: ['watch', 'spectacle'],
  },
  {
    id: 'il-day77-pocket-knief',
    name: 'Pocket Knief',
    filename: 'day77-pocket-knief.svg',
    source: 'illlustrations',
    tags: ['pocket', 'knief'],
  },
  {
    id: 'il-day78-wallet',
    name: 'Wallet',
    filename: 'day78-wallet.svg',
    source: 'illlustrations',
    tags: ['wallet'],
  },
  {
    id: 'il-day79-coffee',
    name: 'Coffee',
    filename: 'day79-coffee.svg',
    source: 'illlustrations',
    tags: ['coffee'],
  },
  {
    id: 'il-day80-tea',
    name: 'Tea',
    filename: 'day80-tea.svg',
    source: 'illlustrations',
    tags: ['tea'],
  },
  {
    id: 'il-day81-ice-cream',
    name: 'Ice Cream',
    filename: 'day81-ice-cream.svg',
    source: 'illlustrations',
    tags: ['ice', 'cream'],
  },
  {
    id: 'il-day82-burger',
    name: 'Burger',
    filename: 'day82-burger.svg',
    source: 'illlustrations',
    tags: ['burger'],
  },
  {
    id: 'il-day83-snowman',
    name: 'Snowman',
    filename: 'day83-snowman.svg',
    source: 'illlustrations',
    tags: ['snowman'],
  },
  {
    id: 'il-day84-reindeer',
    name: 'Reindeer',
    filename: 'day84-reindeer.svg',
    source: 'illlustrations',
    tags: ['reindeer'],
  },
  {
    id: 'il-day85-socks',
    name: 'Socks',
    filename: 'day85-socks.svg',
    source: 'illlustrations',
    tags: ['socks'],
  },
  {
    id: 'il-day86-candle',
    name: 'Candle',
    filename: 'day86-candle.svg',
    source: 'illlustrations',
    tags: ['candle'],
  },
  {
    id: 'il-day87-chritmas-ball',
    name: 'Chritmas Ball',
    filename: 'day87-chritmas-ball.svg',
    source: 'illlustrations',
    tags: ['chritmas', 'ball'],
  },
  {
    id: 'il-day88-jingle-bell',
    name: 'Jingle Bell',
    filename: 'day88-jingle-bell.svg',
    source: 'illlustrations',
    tags: ['jingle', 'bell'],
  },
  {
    id: 'il-day89-christmas-gift',
    name: 'Christmas Gift',
    filename: 'day89-christmas-gift.svg',
    source: 'illlustrations',
    tags: ['christmas', 'gift'],
  },
  {
    id: 'il-day90-santa',
    name: 'Santa',
    filename: 'day90-santa.svg',
    source: 'illlustrations',
    tags: ['santa'],
  },
  {
    id: 'il-day91-merry-christmas',
    name: 'Merry Christmas',
    filename: 'day91-merry-christmas.svg',
    source: 'illlustrations',
    tags: ['merry', 'christmas'],
  },
  {
    id: 'il-day92-freelancing',
    name: 'Freelancing',
    filename: 'day92-freelancing.svg',
    source: 'illlustrations',
    tags: ['freelancing'],
  },
  {
    id: 'il-day93-programing',
    name: 'Programing',
    filename: 'day93-programing.svg',
    source: 'illlustrations',
    tags: ['programing'],
  },
  {
    id: 'il-day94-ui-ux',
    name: 'Ui Ux',
    filename: 'day94-ui-ux.svg',
    source: 'illlustrations',
    tags: ['ui', 'ux'],
  },
  {
    id: 'il-day95-app-development',
    name: 'App Development',
    filename: 'day95-app-development.svg',
    source: 'illlustrations',
    tags: ['app', 'development'],
  },
  {
    id: 'il-day96-camping',
    name: 'Camping',
    filename: 'day96-camping.svg',
    source: 'illlustrations',
    tags: ['camping'],
  },
  {
    id: 'il-day97-champagne',
    name: 'Champagne',
    filename: 'day97-champagne.svg',
    source: 'illlustrations',
    tags: ['champagne'],
  },
  {
    id: 'il-day98-junk-boat',
    name: 'Junk Boat',
    filename: 'day98-junk-boat.svg',
    source: 'illlustrations',
    tags: ['junk', 'boat'],
  },
  {
    id: 'il-day99-pirate-boat',
    name: 'Pirate Boat',
    filename: 'day99-pirate-boat.svg',
    source: 'illlustrations',
    tags: ['pirate', 'boat'],
  },
  {
    id: 'il-day100-the-snail',
    name: 'The Snail',
    filename: 'day100-the-snail.svg',
    source: 'illlustrations',
    tags: ['the', 'snail'],
  },
];
