/**
 * Open Peeps Illustration Definitions
 *
 * 189 people templates by Pablo Stanley (https://openpeeps.com/),
 * CC0 / public domain. Rendered in native colors. Mix-&-match component
 * atoms are intentionally excluded — only complete illustrations here.
 */

import type { SvgDef } from './types';

export const OPENPEEPS: SvgDef[] = [
  {
    id: 'op-bust-mask-1',
    name: 'Maske 1',
    filename: 'bust-mask-1.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-2',
    name: 'Maske 2',
    filename: 'bust-mask-2.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-3',
    name: 'Maske 3',
    filename: 'bust-mask-3.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-4',
    name: 'Maske 4',
    filename: 'bust-mask-4.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-5',
    name: 'Maske 5',
    filename: 'bust-mask-5.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-6',
    name: 'Maske 6',
    filename: 'bust-mask-6.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-7',
    name: 'Maske 7',
    filename: 'bust-mask-7.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-8',
    name: 'Maske 8',
    filename: 'bust-mask-8.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-9',
    name: 'Maske 9',
    filename: 'bust-mask-9.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-10',
    name: 'Maske 10',
    filename: 'bust-mask-10.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-11',
    name: 'Maske 11',
    filename: 'bust-mask-11.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-12',
    name: 'Maske 12',
    filename: 'bust-mask-12.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-13',
    name: 'Maske 13',
    filename: 'bust-mask-13.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-14',
    name: 'Maske 14',
    filename: 'bust-mask-14.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-15',
    name: 'Maske 15',
    filename: 'bust-mask-15.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-bust-mask-16',
    name: 'Maske 16',
    filename: 'bust-mask-16.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'portrait'],
    category: 'Menschen',
  },
  {
    id: 'op-doc-nurse-1',
    name: 'Doc Nurse 1',
    filename: 'doc-nurse-1.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep'],
    category: 'Menschen',
  },
  {
    id: 'op-doc-nurse-2',
    name: 'Doc Nurse 2',
    filename: 'doc-nurse-2.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep'],
    category: 'Menschen',
  },
  {
    id: 'op-doc-nurse-3',
    name: 'Doc Nurse 3',
    filename: 'doc-nurse-3.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep'],
    category: 'Menschen',
  },
  {
    id: 'op-doc-nurse-4',
    name: 'Doc Nurse 4',
    filename: 'doc-nurse-4.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep'],
    category: 'Menschen',
  },
  {
    id: 'op-doc-nurse-5',
    name: 'Doc Nurse 5',
    filename: 'doc-nurse-5.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep'],
    category: 'Menschen',
  },
  {
    id: 'op-doc-nurse-6',
    name: 'Doc Nurse 6',
    filename: 'doc-nurse-6.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep'],
    category: 'Menschen',
  },
  {
    id: 'op-doc-nurse-7',
    name: 'Doc Nurse 7',
    filename: 'doc-nurse-7.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-1',
    name: 'Peep 1',
    filename: 'peep-1.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-2',
    name: 'Peep 2',
    filename: 'peep-2.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-3',
    name: 'Peep 3',
    filename: 'peep-3.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-4',
    name: 'Peep 4',
    filename: 'peep-4.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-5',
    name: 'Peep 5',
    filename: 'peep-5.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-6',
    name: 'Peep 6',
    filename: 'peep-6.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-7',
    name: 'Peep 7',
    filename: 'peep-7.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-8',
    name: 'Peep 8',
    filename: 'peep-8.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-9',
    name: 'Peep 9',
    filename: 'peep-9.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-10',
    name: 'Peep 10',
    filename: 'peep-10.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-11',
    name: 'Peep 11',
    filename: 'peep-11.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-12',
    name: 'Peep 12',
    filename: 'peep-12.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-13',
    name: 'Peep 13',
    filename: 'peep-13.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-14',
    name: 'Peep 14',
    filename: 'peep-14.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-15',
    name: 'Peep 15',
    filename: 'peep-15.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-16',
    name: 'Peep 16',
    filename: 'peep-16.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-17',
    name: 'Peep 17',
    filename: 'peep-17.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-18',
    name: 'Peep 18',
    filename: 'peep-18.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-19',
    name: 'Peep 19',
    filename: 'peep-19.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-20',
    name: 'Peep 20',
    filename: 'peep-20.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-21',
    name: 'Peep 21',
    filename: 'peep-21.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-22',
    name: 'Peep 22',
    filename: 'peep-22.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-23',
    name: 'Peep 23',
    filename: 'peep-23.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-24',
    name: 'Peep 24',
    filename: 'peep-24.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-25',
    name: 'Peep 25',
    filename: 'peep-25.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-26',
    name: 'Peep 26',
    filename: 'peep-26.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-27',
    name: 'Peep 27',
    filename: 'peep-27.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-28',
    name: 'Peep 28',
    filename: 'peep-28.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-29',
    name: 'Peep 29',
    filename: 'peep-29.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-30',
    name: 'Peep 30',
    filename: 'peep-30.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-31',
    name: 'Peep 31',
    filename: 'peep-31.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-32',
    name: 'Peep 32',
    filename: 'peep-32.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-33',
    name: 'Peep 33',
    filename: 'peep-33.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-34',
    name: 'Peep 34',
    filename: 'peep-34.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-35',
    name: 'Peep 35',
    filename: 'peep-35.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-36',
    name: 'Peep 36',
    filename: 'peep-36.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-37',
    name: 'Peep 37',
    filename: 'peep-37.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-38',
    name: 'Peep 38',
    filename: 'peep-38.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-39',
    name: 'Peep 39',
    filename: 'peep-39.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-40',
    name: 'Peep 40',
    filename: 'peep-40.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-41',
    name: 'Peep 41',
    filename: 'peep-41.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-42',
    name: 'Peep 42',
    filename: 'peep-42.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-43',
    name: 'Peep 43',
    filename: 'peep-43.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-44',
    name: 'Peep 44',
    filename: 'peep-44.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-45',
    name: 'Peep 45',
    filename: 'peep-45.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-46',
    name: 'Peep 46',
    filename: 'peep-46.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-47',
    name: 'Peep 47',
    filename: 'peep-47.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-48',
    name: 'Peep 48',
    filename: 'peep-48.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-49',
    name: 'Peep 49',
    filename: 'peep-49.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-50',
    name: 'Peep 50',
    filename: 'peep-50.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-51',
    name: 'Peep 51',
    filename: 'peep-51.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-52',
    name: 'Peep 52',
    filename: 'peep-52.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-53',
    name: 'Peep 53',
    filename: 'peep-53.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-54',
    name: 'Peep 54',
    filename: 'peep-54.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-55',
    name: 'Peep 55',
    filename: 'peep-55.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-56',
    name: 'Peep 56',
    filename: 'peep-56.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-57',
    name: 'Peep 57',
    filename: 'peep-57.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-58',
    name: 'Peep 58',
    filename: 'peep-58.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-59',
    name: 'Peep 59',
    filename: 'peep-59.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-60',
    name: 'Peep 60',
    filename: 'peep-60.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-61',
    name: 'Peep 61',
    filename: 'peep-61.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-62',
    name: 'Peep 62',
    filename: 'peep-62.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-63',
    name: 'Peep 63',
    filename: 'peep-63.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-64',
    name: 'Peep 64',
    filename: 'peep-64.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-65',
    name: 'Peep 65',
    filename: 'peep-65.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-66',
    name: 'Peep 66',
    filename: 'peep-66.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-67',
    name: 'Peep 67',
    filename: 'peep-67.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-68',
    name: 'Peep 68',
    filename: 'peep-68.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-69',
    name: 'Peep 69',
    filename: 'peep-69.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-70',
    name: 'Peep 70',
    filename: 'peep-70.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-71',
    name: 'Peep 71',
    filename: 'peep-71.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-72',
    name: 'Peep 72',
    filename: 'peep-72.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-73',
    name: 'Peep 73',
    filename: 'peep-73.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-74',
    name: 'Peep 74',
    filename: 'peep-74.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-75',
    name: 'Peep 75',
    filename: 'peep-75.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-76',
    name: 'Peep 76',
    filename: 'peep-76.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-77',
    name: 'Peep 77',
    filename: 'peep-77.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-78',
    name: 'Peep 78',
    filename: 'peep-78.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-79',
    name: 'Peep 79',
    filename: 'peep-79.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-80',
    name: 'Peep 80',
    filename: 'peep-80.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-81',
    name: 'Peep 81',
    filename: 'peep-81.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-82',
    name: 'Peep 82',
    filename: 'peep-82.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-83',
    name: 'Peep 83',
    filename: 'peep-83.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-84',
    name: 'Peep 84',
    filename: 'peep-84.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-85',
    name: 'Peep 85',
    filename: 'peep-85.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-86',
    name: 'Peep 86',
    filename: 'peep-86.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-87',
    name: 'Peep 87',
    filename: 'peep-87.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-88',
    name: 'Peep 88',
    filename: 'peep-88.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-89',
    name: 'Peep 89',
    filename: 'peep-89.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-90',
    name: 'Peep 90',
    filename: 'peep-90.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-91',
    name: 'Peep 91',
    filename: 'peep-91.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-92',
    name: 'Peep 92',
    filename: 'peep-92.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-93',
    name: 'Peep 93',
    filename: 'peep-93.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-94',
    name: 'Peep 94',
    filename: 'peep-94.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-95',
    name: 'Peep 95',
    filename: 'peep-95.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-96',
    name: 'Peep 96',
    filename: 'peep-96.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-97',
    name: 'Peep 97',
    filename: 'peep-97.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-98',
    name: 'Peep 98',
    filename: 'peep-98.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-99',
    name: 'Peep 99',
    filename: 'peep-99.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-100',
    name: 'Peep 100',
    filename: 'peep-100.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-101',
    name: 'Peep 101',
    filename: 'peep-101.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-102',
    name: 'Peep 102',
    filename: 'peep-102.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-103',
    name: 'Peep 103',
    filename: 'peep-103.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-104',
    name: 'Peep 104',
    filename: 'peep-104.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-105',
    name: 'Peep 105',
    filename: 'peep-105.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'portrait', 'bueste'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-1',
    name: 'Sitzend 1',
    filename: 'peep-sitting-1.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-2',
    name: 'Sitzend 2',
    filename: 'peep-sitting-2.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-3',
    name: 'Sitzend 3',
    filename: 'peep-sitting-3.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-4',
    name: 'Sitzend 4',
    filename: 'peep-sitting-4.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-5',
    name: 'Sitzend 5',
    filename: 'peep-sitting-5.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-6',
    name: 'Sitzend 6',
    filename: 'peep-sitting-6.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-7',
    name: 'Sitzend 7',
    filename: 'peep-sitting-7.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-8',
    name: 'Sitzend 8',
    filename: 'peep-sitting-8.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-9',
    name: 'Sitzend 9',
    filename: 'peep-sitting-9.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-10',
    name: 'Sitzend 10',
    filename: 'peep-sitting-10.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-11',
    name: 'Sitzend 11',
    filename: 'peep-sitting-11.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-12',
    name: 'Sitzend 12',
    filename: 'peep-sitting-12.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-13',
    name: 'Sitzend 13',
    filename: 'peep-sitting-13.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-14',
    name: 'Sitzend 14',
    filename: 'peep-sitting-14.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-15',
    name: 'Sitzend 15',
    filename: 'peep-sitting-15.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-16',
    name: 'Sitzend 16',
    filename: 'peep-sitting-16.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-17',
    name: 'Sitzend 17',
    filename: 'peep-sitting-17.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-sitting-18',
    name: 'Sitzend 18',
    filename: 'peep-sitting-18.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'sitzend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-1',
    name: 'Stehend 1',
    filename: 'peep-standing-1.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-2',
    name: 'Stehend 2',
    filename: 'peep-standing-2.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-3',
    name: 'Stehend 3',
    filename: 'peep-standing-3.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-4',
    name: 'Stehend 4',
    filename: 'peep-standing-4.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-5',
    name: 'Stehend 5',
    filename: 'peep-standing-5.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-6',
    name: 'Stehend 6',
    filename: 'peep-standing-6.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-7',
    name: 'Stehend 7',
    filename: 'peep-standing-7.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-8',
    name: 'Stehend 8',
    filename: 'peep-standing-8.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-9',
    name: 'Stehend 9',
    filename: 'peep-standing-9.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-10',
    name: 'Stehend 10',
    filename: 'peep-standing-10.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-11',
    name: 'Stehend 11',
    filename: 'peep-standing-11.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-12',
    name: 'Stehend 12',
    filename: 'peep-standing-12.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-13',
    name: 'Stehend 13',
    filename: 'peep-standing-13.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-14',
    name: 'Stehend 14',
    filename: 'peep-standing-14.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-15',
    name: 'Stehend 15',
    filename: 'peep-standing-15.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-16',
    name: 'Stehend 16',
    filename: 'peep-standing-16.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-17',
    name: 'Stehend 17',
    filename: 'peep-standing-17.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-18',
    name: 'Stehend 18',
    filename: 'peep-standing-18.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-19',
    name: 'Stehend 19',
    filename: 'peep-standing-19.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-20',
    name: 'Stehend 20',
    filename: 'peep-standing-20.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-21',
    name: 'Stehend 21',
    filename: 'peep-standing-21.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-22',
    name: 'Stehend 22',
    filename: 'peep-standing-22.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-23',
    name: 'Stehend 23',
    filename: 'peep-standing-23.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-24',
    name: 'Stehend 24',
    filename: 'peep-standing-24.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-25',
    name: 'Stehend 25',
    filename: 'peep-standing-25.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-26',
    name: 'Stehend 26',
    filename: 'peep-standing-26.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-27',
    name: 'Stehend 27',
    filename: 'peep-standing-27.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-28',
    name: 'Stehend 28',
    filename: 'peep-standing-28.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-29',
    name: 'Stehend 29',
    filename: 'peep-standing-29.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-peep-standing-30',
    name: 'Stehend 30',
    filename: 'peep-standing-30.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'stehend'],
    category: 'Menschen',
  },
  {
    id: 'op-pose-mask-1',
    name: 'Maske Pose 1',
    filename: 'pose-mask-1.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'figur'],
    category: 'Menschen',
  },
  {
    id: 'op-pose-mask-2',
    name: 'Maske Pose 2',
    filename: 'pose-mask-2.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'figur'],
    category: 'Menschen',
  },
  {
    id: 'op-pose-mask-3',
    name: 'Maske Pose 3',
    filename: 'pose-mask-3.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'figur'],
    category: 'Menschen',
  },
  {
    id: 'op-pose-mask-4',
    name: 'Maske Pose 4',
    filename: 'pose-mask-4.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'figur'],
    category: 'Menschen',
  },
  {
    id: 'op-pose-mask-5',
    name: 'Maske Pose 5',
    filename: 'pose-mask-5.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'figur'],
    category: 'Menschen',
  },
  {
    id: 'op-pose-mask-6',
    name: 'Maske Pose 6',
    filename: 'pose-mask-6.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'figur'],
    category: 'Menschen',
  },
  {
    id: 'op-pose-mask-7',
    name: 'Maske Pose 7',
    filename: 'pose-mask-7.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'figur'],
    category: 'Menschen',
  },
  {
    id: 'op-pose-mask-8',
    name: 'Maske Pose 8',
    filename: 'pose-mask-8.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep', 'maske', 'figur'],
    category: 'Menschen',
  },
  {
    id: 'op-sit-mask-1',
    name: 'Sit Mask 1',
    filename: 'sit-mask-1.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep'],
    category: 'Menschen',
  },
  {
    id: 'op-sit-mask-2',
    name: 'Sit Mask 2',
    filename: 'sit-mask-2.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep'],
    category: 'Menschen',
  },
  {
    id: 'op-sit-mask-3',
    name: 'Sit Mask 3',
    filename: 'sit-mask-3.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep'],
    category: 'Menschen',
  },
  {
    id: 'op-sit-mask-4',
    name: 'Sit Mask 4',
    filename: 'sit-mask-4.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep'],
    category: 'Menschen',
  },
  {
    id: 'op-sit-mask-5',
    name: 'Sit Mask 5',
    filename: 'sit-mask-5.svg',
    source: 'openpeeps',
    tags: ['person', 'mensch', 'peep'],
    category: 'Menschen',
  },
];
