/**
 * Transhumans Illustration Definitions
 *
 * 38 illustrations by Pablo Stanley (https://transhumans.xyz/),
 * free for personal and commercial use. Rendered in native colors.
 */

import type { SvgDef } from './types';

export const TRANSHUMANS: SvgDef[] = [
  {
    id: 'th-astro',
    name: 'Astro',
    filename: 'astro.svg',
    source: 'transhumans',
    tags: ['astro', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-bueno',
    name: 'Bueno',
    filename: 'bueno.svg',
    source: 'transhumans',
    tags: ['bueno', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-chaotic-good',
    name: 'Chaotic Good',
    filename: 'chaotic-good.svg',
    source: 'transhumans',
    tags: ['chaotic', 'good', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-chillin',
    name: 'Chillin',
    filename: 'chillin.svg',
    source: 'transhumans',
    tags: ['chillin', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-chilly',
    name: 'Chilly',
    filename: 'chilly.svg',
    source: 'transhumans',
    tags: ['chilly', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-coffee',
    name: 'Coffee',
    filename: 'coffee.svg',
    source: 'transhumans',
    tags: ['coffee', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-consumer',
    name: 'Consumer',
    filename: 'consumer.svg',
    source: 'transhumans',
    tags: ['consumer', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-cube-leg',
    name: 'Cube Leg',
    filename: 'cube-leg.svg',
    source: 'transhumans',
    tags: ['cube', 'leg', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-ecto-plasma',
    name: 'Ecto Plasma',
    filename: 'ecto-plasma.svg',
    source: 'transhumans',
    tags: ['ecto', 'plasma', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-entertainment',
    name: 'Entertainment',
    filename: 'entertainment.svg',
    source: 'transhumans',
    tags: ['entertainment', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-experiments',
    name: 'Experiments',
    filename: 'experiments.svg',
    source: 'transhumans',
    tags: ['experiments', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-feliz',
    name: 'Feliz',
    filename: 'feliz.svg',
    source: 'transhumans',
    tags: ['feliz', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-fling',
    name: 'Fling',
    filename: 'fling.svg',
    source: 'transhumans',
    tags: ['fling', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-gamestation',
    name: 'Gamestation',
    filename: 'gamestation.svg',
    source: 'transhumans',
    tags: ['gamestation', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-groceries',
    name: 'Groceries',
    filename: 'groceries.svg',
    source: 'transhumans',
    tags: ['groceries', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-growth',
    name: 'Growth',
    filename: 'growth.svg',
    source: 'transhumans',
    tags: ['growth', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-jumping',
    name: 'Jumping',
    filename: 'jumping.svg',
    source: 'transhumans',
    tags: ['jumping', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-kiddo',
    name: 'Kiddo',
    filename: 'kiddo.svg',
    source: 'transhumans',
    tags: ['kiddo', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-late-for-class',
    name: 'Late for Class',
    filename: 'late-for-class.svg',
    source: 'transhumans',
    tags: ['late', 'for', 'class', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-looking-ahead',
    name: 'Looking Ahead',
    filename: 'looking-ahead.svg',
    source: 'transhumans',
    tags: ['looking', 'ahead', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-mask',
    name: 'Mask',
    filename: 'mask.svg',
    source: 'transhumans',
    tags: ['mask', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-mechanical-love',
    name: 'Mechanical Love',
    filename: 'mechanical-love.svg',
    source: 'transhumans',
    tags: ['mechanical', 'love', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-meela-pantalones',
    name: 'Meela Pantalones',
    filename: 'meela-pantalones.svg',
    source: 'transhumans',
    tags: ['meela', 'pantalones', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-new-beginnings',
    name: 'New Beginnings',
    filename: 'new-beginnings.svg',
    source: 'transhumans',
    tags: ['new', 'beginnings', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-pacheco',
    name: 'Pacheco',
    filename: 'pacheco.svg',
    source: 'transhumans',
    tags: ['pacheco', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-pilot',
    name: 'Pilot',
    filename: 'pilot.svg',
    source: 'transhumans',
    tags: ['pilot', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-plants',
    name: 'Plants',
    filename: 'plants.svg',
    source: 'transhumans',
    tags: ['plants', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-polka-pup',
    name: 'Polka Pup',
    filename: 'polka-pup.svg',
    source: 'transhumans',
    tags: ['polka', 'pup', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-pondering',
    name: 'Pondering',
    filename: 'pondering.svg',
    source: 'transhumans',
    tags: ['pondering', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-puppy',
    name: 'Puppy',
    filename: 'puppy.svg',
    source: 'transhumans',
    tags: ['puppy', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-reflecting',
    name: 'Reflecting',
    filename: 'reflecting.svg',
    source: 'transhumans',
    tags: ['reflecting', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-roboto',
    name: 'Roboto',
    filename: 'roboto.svg',
    source: 'transhumans',
    tags: ['roboto', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-rogue',
    name: 'Rogue',
    filename: 'rogue.svg',
    source: 'transhumans',
    tags: ['rogue', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-runner',
    name: 'Runner',
    filename: 'runner.svg',
    source: 'transhumans',
    tags: ['runner', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-waiting',
    name: 'Waiting',
    filename: 'waiting.svg',
    source: 'transhumans',
    tags: ['waiting', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-walking-contradiction',
    name: 'Walking Contradiction',
    filename: 'walking-contradiction.svg',
    source: 'transhumans',
    tags: ['walking', 'contradiction', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-whoa',
    name: 'Whoa',
    filename: 'whoa.svg',
    source: 'transhumans',
    tags: ['whoa', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
  {
    id: 'th-wont-stop',
    name: 'Wont Stop',
    filename: 'wont-stop.svg',
    source: 'transhumans',
    tags: ['wont', 'stop', 'person', 'mensch', 'illustration'],
    category: 'Menschen',
  },
];
