/**
 * Codegen — read packages/shared/src/agents/skills/*.md and emit
 * `index.generated.ts` as a typed `SKILLS` array.
 *
 * Each markdown file is one skill: YAML frontmatter for metadata
 * (validated by `skillFrontmatterSchema` from @gruenerator/contracts),
 * markdown body becomes `skillSystemPrompt` (empty body → field omitted).
 *
 * Ordering: numeric `order` ascending, ties break alphabetically by `mention`.
 *
 * Run via `pnpm --filter @gruenerator/shared build:skills`. Pre-bound to
 * `prebuild` / `predev` so consumers don't need to remember it.
 *
 * Watch mode: `--watch` re-emits on any *.md change (chokidar).
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { skillFrontmatterSchema, type SkillFrontmatter } from '@gruenerator/contracts';
import chokidar from 'chokidar';
import matter from 'gray-matter';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SKILLS_DIR = resolve(__dirname, '../src/agents/skills');
const OUT_PATH = resolve(SKILLS_DIR, 'index.generated.ts');

interface ParsedSkill {
  filename: string;
  frontmatter: SkillFrontmatter;
  body: string;
}

function parseAll(): ParsedSkill[] {
  const files = readdirSync(SKILLS_DIR).filter((f) => f.endsWith('.md'));
  if (files.length === 0) {
    throw new Error(`[build-skills] No *.md files in ${SKILLS_DIR}`);
  }
  return files.map((filename) => {
    const raw = readFileSync(resolve(SKILLS_DIR, filename), 'utf8');
    const { data, content } = matter(raw);
    const result = skillFrontmatterSchema.safeParse(data);
    if (!result.success) {
      const issues = result.error.issues
        .map((i) => `  · ${i.path.join('.')}: ${i.message}`)
        .join('\n');
      throw new Error(`[build-skills] Invalid frontmatter in ${filename}:\n${issues}`);
    }
    return { filename, frontmatter: result.data, body: content.trim() };
  });
}

function detectDuplicates(skills: readonly ParsedSkill[]): void {
  const seen = new Map<string, string>();
  for (const skill of skills) {
    const prior = seen.get(skill.frontmatter.mention);
    if (prior) {
      throw new Error(
        `[build-skills] Duplicate mention "${skill.frontmatter.mention}" in ${skill.filename} (also in ${prior})`
      );
    }
    seen.set(skill.frontmatter.mention, skill.filename);
  }
}

function sortSkills(skills: readonly ParsedSkill[]): ParsedSkill[] {
  return [...skills].sort((a, b) => {
    const ao = a.frontmatter.order ?? Number.POSITIVE_INFINITY;
    const bo = b.frontmatter.order ?? Number.POSITIVE_INFINITY;
    if (ao !== bo) return ao - bo;
    return a.frontmatter.mention.localeCompare(b.frontmatter.mention);
  });
}

function emit(skills: readonly ParsedSkill[]): string {
  const lines: string[] = [
    '// AUTO-GENERATED by packages/shared/scripts/build-skills.ts — do not edit.',
    '// Source: packages/shared/src/agents/skills/*.md',
    '// Re-run `pnpm --filter @gruenerator/shared build:skills` after editing.',
    '',
    "import type { SystemSkill } from './types.js';",
    '',
    'export const SKILLS = [',
  ];
  for (const skill of skills) {
    lines.push('  {');
    for (const [key, value] of Object.entries(skill.frontmatter)) {
      if (key === 'order') continue;
      lines.push(`    ${key}: ${JSON.stringify(value)},`);
    }
    if (skill.body) {
      lines.push(`    skillSystemPrompt: ${JSON.stringify(skill.body)},`);
    }
    lines.push('  },');
  }
  lines.push('] as const satisfies readonly SystemSkill[];');
  lines.push('');
  return lines.join('\n');
}

function build(): void {
  const parsed = parseAll();
  detectDuplicates(parsed);
  const sorted = sortSkills(parsed);
  writeFileSync(OUT_PATH, emit(sorted));
  console.log(`[build-skills] wrote ${sorted.length} skills → ${OUT_PATH}`);
}

const watchMode = process.argv.includes('--watch');
build();
if (watchMode) {
  console.log(`[build-skills] watching ${SKILLS_DIR}/*.md`);
  chokidar.watch(`${SKILLS_DIR}/*.md`, { ignoreInitial: true }).on('all', (event, path) => {
    try {
      build();
      console.log(`[build-skills] regenerated after ${event} on ${path}`);
    } catch (err) {
      console.error(err instanceof Error ? err.message : String(err));
    }
  });
}
