/**
 * Codegen — read packages/shared/src/agents/definitions/*.md and emit
 * `index.generated.ts` as a typed `SYSTEM_AGENT_DEFINITIONS` array.
 *
 * Each markdown file is one hand-written system agent: YAML frontmatter for all
 * structured metadata (validated by `agentFrontmatterSchema` from
 * @gruenerator/contracts), markdown body becomes the agent's `systemRole`
 * prompt. Sibling to `build-skills.ts` — same pattern, so the heavy prompts that
 * used to sit inline as escaped TS string literals are now reviewable markdown.
 *
 * The per-Landesverband agents (lvPrAgents.ts / lvBuergerAgents.ts) stay as
 * template builders — one template fans out to N agents, so per-file extraction
 * would only duplicate them. system.ts appends them after these definitions.
 *
 * Ordering: numeric `order` ascending, ties break alphabetically by `identifier`.
 *
 * Run via `pnpm --filter @gruenerator/shared build:agents`. Pre-bound to
 * `prebuild` / `predev` so consumers don't need to remember it.
 *
 * Watch mode: `--watch` re-emits on any *.md change (chokidar).
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { agentFrontmatterSchema, type AgentFrontmatter } from '@gruenerator/contracts';
import chokidar from 'chokidar';
import matter from 'gray-matter';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DEFINITIONS_DIR = resolve(__dirname, '../src/agents/definitions');
const OUT_PATH = resolve(DEFINITIONS_DIR, 'index.generated.ts');

interface ParsedAgent {
  filename: string;
  frontmatter: AgentFrontmatter;
  body: string;
}

function parseAll(): ParsedAgent[] {
  const files = readdirSync(DEFINITIONS_DIR).filter((f) => f.endsWith('.md'));
  if (files.length === 0) {
    throw new Error(`[build-agents] No *.md files in ${DEFINITIONS_DIR}`);
  }
  return files.map((filename) => {
    const raw = readFileSync(resolve(DEFINITIONS_DIR, filename), 'utf8');
    const { data, content } = matter(raw);
    const result = agentFrontmatterSchema.safeParse(data);
    if (!result.success) {
      const issues = result.error.issues
        .map((i) => `  · ${i.path.join('.')}: ${i.message}`)
        .join('\n');
      throw new Error(`[build-agents] Invalid frontmatter in ${filename}:\n${issues}`);
    }
    return { filename, frontmatter: result.data, body: content.trim() };
  });
}

function detectDuplicates(agents: readonly ParsedAgent[]): void {
  const seen = new Map<string, string>();
  for (const agent of agents) {
    const prior = seen.get(agent.frontmatter.identifier);
    if (prior) {
      throw new Error(
        `[build-agents] Duplicate identifier "${agent.frontmatter.identifier}" in ${agent.filename} (also in ${prior})`
      );
    }
    seen.set(agent.frontmatter.identifier, agent.filename);
  }
}

function sortAgents(agents: readonly ParsedAgent[]): ParsedAgent[] {
  return [...agents].sort((a, b) => {
    const ao = a.frontmatter.order ?? Number.POSITIVE_INFINITY;
    const bo = b.frontmatter.order ?? Number.POSITIVE_INFINITY;
    if (ao !== bo) return ao - bo;
    return a.frontmatter.identifier.localeCompare(b.frontmatter.identifier);
  });
}

function emit(agents: readonly ParsedAgent[]): string {
  const lines: string[] = [
    '// AUTO-GENERATED by packages/shared/scripts/build-agents.ts — do not edit.',
    '// Source: packages/shared/src/agents/definitions/*.md',
    '// Re-run `pnpm --filter @gruenerator/shared build:agents` after editing.',
    '',
    "import type { Agent } from '../types.js';",
    '',
    'export const SYSTEM_AGENT_DEFINITIONS = [',
  ];
  for (const agent of agents) {
    lines.push('  {');
    for (const [key, value] of Object.entries(agent.frontmatter)) {
      if (key === 'order') continue;
      lines.push(`    ${key}: ${JSON.stringify(value)},`);
    }
    lines.push(`    systemRole: ${JSON.stringify(agent.body)},`);
    lines.push('  },');
  }
  lines.push('] as const satisfies readonly Agent[];');
  lines.push('');
  return lines.join('\n');
}

function build(): void {
  const parsed = parseAll();
  detectDuplicates(parsed);
  const sorted = sortAgents(parsed);
  writeFileSync(OUT_PATH, emit(sorted));
  console.log(`[build-agents] wrote ${sorted.length} agents → ${OUT_PATH}`);
}

const watchMode = process.argv.includes('--watch');
build();
if (watchMode) {
  console.log(`[build-agents] watching ${DEFINITIONS_DIR}/*.md`);
  // chokidar v4+ dropped glob support — watch the dir and filter to *.md
  // (skips the generated index.generated.ts, avoiding a write→rebuild loop).
  chokidar.watch(DEFINITIONS_DIR, { ignoreInitial: true }).on('all', (event, path) => {
    if (!path.endsWith('.md')) return;
    try {
      build();
      console.log(`[build-agents] regenerated after ${event} on ${path}`);
    } catch (err) {
      console.error(err instanceof Error ? err.message : String(err));
    }
  });
}
