// ... existing code ...
// Entferne diese Zeilen, da die Route jetzt in routes.js registriert wird
// const wahlpruefsteinBundestagswahl = require('./routes/wahlpruefsteinbundestagswahl');
// app.use('/api/wahlpruefsteinbundestagswahl', wahlpruefsteinBundestagswahl); 
// ... existing code ... 