import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// One sidebar per app area (navigation model C): the navbar's docSidebar
// items switch between them, so a reader only ever sees the active area.
// Page order inside an area still comes from each doc's sidebar_position.
// The sidebar ids are referenced by src/nav/sections.ts — keep them in sync.
//
// webinare.md and bildnachweise.md are deliberately in no sidebar: they are
// standalone utility pages, linked from the navbar dropdown and the footer.
const sidebars: SidebarsConfig = {
  ueberSidebar: [{ type: 'autogenerated', dirName: 'ueber-den-gruenerator' }],
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  chatSidebar: [{ type: 'autogenerated', dirName: 'chat' }],
  officeSidebar: [{ type: 'autogenerated', dirName: 'office' }],
  wissenSidebar: [{ type: 'autogenerated', dirName: 'wissen' }],
  grueneratorenSidebar: [{ type: 'autogenerated', dirName: 'grueneratoren' }],
  kontoSidebar: [{ type: 'autogenerated', dirName: 'konto' }],
  integrationenSidebar: [{ type: 'autogenerated', dirName: 'integrationen' }],
  grundlagenSidebar: [{ type: 'autogenerated', dirName: 'grundlagen' }],
  archivSidebar: [{ type: 'autogenerated', dirName: 'archiv' }],
};

export default sidebars;
