import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// One sidebar per app area (navigation model C): the navbar's docSidebar
// items switch between them, so a reader only ever sees the active area.
// Page order inside an area still comes from each doc's sidebar_position.
// The sidebar ids are referenced by src/nav/sections.ts — keep them in sync.
//
// webinare.md and bildnachweise.md are deliberately in no sidebar: they are
// standalone utility pages, linked from the navbar dropdown and the footer.
const sidebars: SidebarsConfig = {
  basicsSidebar: [{ type: 'autogenerated', dirName: 'basics' }],
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  chatSidebar: [{ type: 'autogenerated', dirName: 'chat' }],
  featuresSidebar: [{ type: 'autogenerated', dirName: 'features' }],
  kontoSidebar: [{ type: 'autogenerated', dirName: 'konto' }],
  integrationenSidebar: [{ type: 'autogenerated', dirName: 'integrationen' }],
  sonstigesSidebar: [{ type: 'autogenerated', dirName: 'sonstiges' }],
  archivSidebar: [{ type: 'autogenerated', dirName: 'archiv' }],
};

export default sidebars;
